<?php

namespace Pionect\VismaSdk\Requests\FixedAsset;

use Illuminate\Support\Collection;
use Pionect\VismaSdk\Dto\FixedAssetDto;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * FixedAsset_GetAll
 */
class FixedAssetGetAllRequest extends Request implements Paginatable
{
    protected Method $method = Method::GET;

    /**
     * @return Collection<FixedAssetDto>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        $data = $response->json();

        return collect($data)->map(
            fn (array $item) => FixedAssetDto::from($item)
        );
    }

    public function resolveEndpoint(): string
    {
        return '/v1/fixedAsset';
    }

    /**
     * @param  null|string  $assetId  Fixed Asset ID that identifies the asset.
     * @param  null|string  $classId  View all fixed assets with this Fixed Asset Class ID.
     * @param  null|string  $status  View all fixed assets with this Status. Available statuses are: Active, Disposed, FullyDepriciated, Hold, Reversed, Suspended.
     * @param  null|string  $fromDate  From 'Placed in service date' inclusive. Date format: YYYY-MM-DD.
     * @param  null|string  $toDate  To 'Placed in service date' inclusive. Date format: YYYY-MM-DD.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|bool  $expandAccounts  Set to True to include accounts and subaccounts. Default value is False
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?string $assetId = null,
        protected ?string $classId = null,
        protected ?string $status = null,
        protected ?string $fromDate = null,
        protected ?string $toDate = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?bool $expandAccounts = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'assetID' => $this->assetId,
            'classID' => $this->classId,
            'status' => $this->status,
            'fromDate' => $this->fromDate,
            'toDate' => $this->toDate,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'expandAccounts' => $this->expandAccounts,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
