<?php

namespace Pionect\VismaSdk\Requests\Project;

use Pionect\VismaSdk\Dto\ProjectDto;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * Project_GetAll
 */
class ProjectGetAllRequest extends Request implements Paginatable
{
    protected $model = ProjectDto::class;

    protected Method $method = Method::GET;

    public function createDtoFromResponse(Response $response): mixed
    {
        $data = $response->json();

        return collect($data)->map(
            fn (array $item) => ProjectDto::from($item)
        );
    }

    public function resolveEndpoint(): string
    {
        return '/v1/project';
    }

    /**
     * @param  null|string  $status  Use drop down and select Status.
     * @param  null|bool  $systemTemplate  If the project is a template
     * @param  null|bool  $visibleInAp  If the project is visible in AP
     * @param  null|string  $startDate  Project’s start date
     * @param  null|bool  $expandAttribute  Expands project atributes
     * @param  null|string  $attributes  Identifies the attributes
     * @param  null|string  $taskStatus  Use drop down and select Status.
     * @param  null|bool  $taskVisibleInAp  If the project task is visible in the Supplier ledger
     * @param  null|bool  $taskVisibleInAr  If the project task is visible in the Customer ledger
     * @param  null|bool  $taskVisibleInCa  If the project task is visible in the Cash management workspace
     * @param  null|bool  $taskVisibleInCr  If the project task is visible in the CRM workspace
     * @param  null|bool  $taskVisibleInEa  If the project task is visible in the Expense workspace
     * @param  null|bool  $taskVisibleInGl  If the project task is visible in the General ledger workspace
     * @param  null|bool  $taskVisibleInIn  If the project task is visible in the Inventory workspace
     * @param  null|bool  $taskVisibleInPo  If the project task is visible in the Purchases workspace
     * @param  null|bool  $taskVisibleInSo  If the project task is visible in the Sales workspace
     * @param  null|bool  $taskVisibleInTa  If the project task is visible in the Time entities workspace
     * @param  null|bool  $nonProject  Set to true to return the non-project.
     * @param  null|string  $publicId  Identifies the Project by its publicId
     * @param  null|string  $restrictedEmployee  ID of the employee where access restrictions apply
     * @param  null|int  $restrictedUser  Id of the odp user where access restrictions apply
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $createdDateTime  Creation date and time.
     * @param  null|string  $createdDateTimeCondition  System-retrieved information for state/condition
     * @param  null|string  $branch  The branch name.
     * @param  null|bool  $onHold  If the project is on hold
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?string $status = null,
        protected ?bool $systemTemplate = null,
        protected ?bool $visibleInAp = null,
        protected ?string $startDate = null,
        protected ?bool $expandAttribute = null,
        protected ?string $attributes = null,
        protected ?string $taskStatus = null,
        protected ?bool $taskVisibleInAp = null,
        protected ?bool $taskVisibleInAr = null,
        protected ?bool $taskVisibleInCa = null,
        protected ?bool $taskVisibleInCr = null,
        protected ?bool $taskVisibleInEa = null,
        protected ?bool $taskVisibleInGl = null,
        protected ?bool $taskVisibleInIn = null,
        protected ?bool $taskVisibleInPo = null,
        protected ?bool $taskVisibleInSo = null,
        protected ?bool $taskVisibleInTa = null,
        protected ?bool $nonProject = null,
        protected ?string $publicId = null,
        protected ?string $restrictedEmployee = null,
        protected ?int $restrictedUser = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?string $createdDateTime = null,
        protected ?string $createdDateTimeCondition = null,
        protected ?string $branch = null,
        protected ?bool $onHold = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'status' => $this->status,
            'systemTemplate' => $this->systemTemplate,
            'visibleInAP' => $this->visibleInAp,
            'startDate' => $this->startDate,
            'expandAttribute' => $this->expandAttribute,
            'attributes' => $this->attributes,
            'taskStatus' => $this->taskStatus,
            'taskVisibleInAp' => $this->taskVisibleInAp,
            'taskVisibleInAr' => $this->taskVisibleInAr,
            'taskVisibleInCa' => $this->taskVisibleInCa,
            'taskVisibleInCr' => $this->taskVisibleInCr,
            'taskVisibleInEa' => $this->taskVisibleInEa,
            'taskVisibleInGl' => $this->taskVisibleInGl,
            'taskVisibleInIn' => $this->taskVisibleInIn,
            'taskVisibleInPo' => $this->taskVisibleInPo,
            'taskVisibleInSo' => $this->taskVisibleInSo,
            'taskVisibleInTa' => $this->taskVisibleInTa,
            'nonProject' => $this->nonProject,
            'publicId' => $this->publicId,
            'restrictedEmployee' => $this->restrictedEmployee,
            'restrictedUser' => $this->restrictedUser,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'createdDateTime' => $this->createdDateTime,
            'createdDateTimeCondition' => $this->createdDateTimeCondition,
            'branch' => $this->branch,
            'onHold' => $this->onHold,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
