<?php

namespace Pionect\VismaSdk\Requests\Inventory;

use Illuminate\Support\Collection;
use Pionect\VismaSdk\Dto\InventoryDto;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * Inventory_GetAll
 *
 * Data for Inventory
 */
class InventoryGetAllRequest extends Request implements Paginatable
{
    protected Method $method = Method::GET;

    /**
     * @return Collection<int, InventoryDto>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        $data = $response->json();

        return collect($data)->map(
            fn (array $item) => InventoryDto::from($item)
        );
    }

    public function resolveEndpoint(): string
    {
        return '/v1/inventory';
    }

    /**
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     *                              MaxPageSize will be set to 5000 from 1. April 2022
     * @param  null|string  $alternateId  Applies for both Stock and Non-stock items.  Some fields in this filter applies only for one of these.
     * @param  null|string  $inventoryNumber  The Item ID.
     * @param  null|int  $salesCategory  The Category ID for the sales category, found on the Attributes tab.
     * @param  null|bool  $addCostPriceStatistics  This filter can be used only for stock items, from the Price/cost information tab.
     * @param  null|string  $attributes  Attributes (additional information) connected to the entity.
     *                                   Examples:
     *                                   {{base}}/inventory?attributes={"AttributeID":"ValueID","AttributeID":"ValueID"}
     *                                   {{base}}/inventory?attributes={"AttributeID":"ValueID1,ValueID2"}
     * @param  null|string  $description  A brief description of the stock item from the Top part of the window.
     * @param  null|string  $availabilityLastModifiedDateTime  System retrieved information.
     * @param  null|string  $availabilityLastModifiedDateTimeCondition  System retrieved information for state/condition.
     * @param  null|array  $inventoryTypes  Filter on one or more inventory types: NonStockItem, LaborItem, ServiceItem, ChargeItem, ExpenseItem, FinishedGoodItem, ComponentPartItem or SubassemblyItem
     * @param  null|bool  $expandCrossReference  These expand fields are by default set to true, but will be changed in the future.
     *                                           Set to true to retrieve information about the cross-references (item ID and suppliers/customers ID for the item connected to the item.
     * @param  null|bool  $expandAttachment  Set to true to retrieve information about the attachments connected to the item.
     * @param  null|bool  $expandAttribute  Set to true to retrieve the attribute descriptions used for the item.
     * @param  null|bool  $expandWarehouseDetail  Set to true to retrieve information about the warehouse connected to the item.
     * @param  null|bool  $expandAccountInformation  Set to true to retrieve information about the account information connected to the item.
     * @param  null|bool  $expandInventoryUnits  Set to true to retrieve information about the units of measure connected to the item.
     * @param  null|bool  $expandSupplierDetails  Set to true to retrieve details about the supplier connected to the item.
     * @param  null|bool  $expandSalesCategories  Set to true to retrieve details about the sales categories connected to the item.
     * @param  null|bool  $expandNote  Set to true to retrieve the note value connected to the item.
     * @param  null|string  $attachmentLastModifiedDateTime  System retrieved information for last modified date and time for attachment.
     * @param  null|string  $attachmentLastModifiedDateTimeCondition  System retrieved information for state/condition for attachment.
     * @param  null|string  $status  The inventory item status
     * @param  null|int  $numberToRead  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|int  $skipRecords  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|string  $greaterThanValue  Greater than value. The item which is the object for this, varies from API to API.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $createdDateTime  Creation date and time.
     * @param  null|string  $createdDateTimeCondition  System-retrieved information for state/condition
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?int $pageSize = null,
        protected ?string $alternateId = null,
        protected ?string $inventoryNumber = null,
        protected ?int $salesCategory = null,
        protected ?bool $addCostPriceStatistics = null,
        protected ?string $attributes = null,
        protected ?string $description = null,
        protected ?string $availabilityLastModifiedDateTime = null,
        protected ?string $availabilityLastModifiedDateTimeCondition = null,
        protected ?array $inventoryTypes = null,
        protected ?bool $expandCrossReference = null,
        protected ?bool $expandAttachment = null,
        protected ?bool $expandAttribute = null,
        protected ?bool $expandWarehouseDetail = null,
        protected ?bool $expandAccountInformation = null,
        protected ?bool $expandInventoryUnits = null,
        protected ?bool $expandSupplierDetails = null,
        protected ?bool $expandSalesCategories = null,
        protected ?bool $expandNote = null,
        protected ?string $attachmentLastModifiedDateTime = null,
        protected ?string $attachmentLastModifiedDateTimeCondition = null,
        protected ?string $status = null,
        protected ?int $numberToRead = null,
        protected ?int $skipRecords = null,
        protected ?string $greaterThanValue = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?string $createdDateTime = null,
        protected ?string $createdDateTimeCondition = null,
        protected ?int $pageNumber = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'pageSize' => $this->pageSize,
            'alternateID' => $this->alternateId,
            'inventoryNumber' => $this->inventoryNumber,
            'salesCategory' => $this->salesCategory,
            'addCostPriceStatistics' => $this->addCostPriceStatistics,
            'attributes' => $this->attributes,
            'description' => $this->description,
            'availabilityLastModifiedDateTime' => $this->availabilityLastModifiedDateTime,
            'availabilityLastModifiedDateTimeCondition' => $this->availabilityLastModifiedDateTimeCondition,
            'inventoryTypes' => $this->inventoryTypes,
            'expandCrossReference' => $this->expandCrossReference,
            'expandAttachment' => $this->expandAttachment,
            'expandAttribute' => $this->expandAttribute,
            'expandWarehouseDetail' => $this->expandWarehouseDetail,
            'expandAccountInformation' => $this->expandAccountInformation,
            'expandInventoryUnits' => $this->expandInventoryUnits,
            'expandSupplierDetails' => $this->expandSupplierDetails,
            'expandSalesCategories' => $this->expandSalesCategories,
            'expandNote' => $this->expandNote,
            'attachmentLastModifiedDateTime' => $this->attachmentLastModifiedDateTime,
            'attachmentLastModifiedDateTimeCondition' => $this->attachmentLastModifiedDateTimeCondition,
            'status' => $this->status,
            'numberToRead' => $this->numberToRead,
            'skipRecords' => $this->skipRecords,
            'greaterThanValue' => $this->greaterThanValue,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'createdDateTime' => $this->createdDateTime,
            'createdDateTimeCondition' => $this->createdDateTimeCondition,
            'pageNumber' => $this->pageNumber,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
