<?php

namespace Pionect\VismaSdk\Requests\GeneralLedgerTransactions;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * GeneralLedgerTransactions_GetAll
 */
class GeneralLedgerTransactionsGetAllCollectionRequest extends Request implements Paginatable
{
    protected Method $method = Method::GET;

    public function resolveEndpoint(): string
    {
        return '/v1/GeneralLedgerTransactions';
    }

    /**
     * @param  null|string  $branch  The branch CD
     * @param  string  $ledger  Mandatory. The ledger in which you want to view the account balances.
     * @param  null|string  $fromPeriod  The financial period that begins the date range of the batches you want to view. Format YYYYPP
     * @param  null|string  $toPeriod  The financial period that ends the date range of the batches you want to view. Format YYYYPP
     * @param  null|string  $account  The account CD for which you want to view activities in the selected financial period.
     * @param  null|string  $subaccountId  The Subaccount
     * @param  null|string  $fromDate  The first date of the interval within the period. Format YYYY-MM-DD
     * @param  null|string  $toDate  The last date of the interval within the selected period. Format YYYY-MM-DD
     * @param  null|bool  $includeUnposted  Checkmark indicating if unposted batches are included.
     * @param  null|bool  $includeUnreleased  Checkmark indicating if unreleased (balanced) batches are included.
     * @param  null|int  $skipRecords  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|int  $numberToRead  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|bool  $expandAccountInfo  By default, if no value is provided, False and the account information will include only Number, Description, Type and GlConsolAccountCD.
     *                                        If True, each transaction returned will include extended information about account.
     * @param  null|bool  $expandBranchInfo  By default, if no value is provided, False and branch information will include only branch number.
     *                                       If True, each transaction returned will include extended information about Branch (number and name).
     * @param  null|bool  $includeTransactionBalance  By default, if no value is provided, False and the transactions returned will not include their balances (fields BegBalance, EndingBalance, CurrBegBalance, CurrEndingBalance)
     *                                                If True, each transaction returned will include its balance.
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?string $branch,
        protected string $ledger,
        protected ?string $fromPeriod = null,
        protected ?string $toPeriod = null,
        protected ?string $account = null,
        protected ?string $subaccountId = null,
        protected ?string $fromDate = null,
        protected ?string $toDate = null,
        protected ?bool $includeUnposted = null,
        protected ?bool $includeUnreleased = null,
        protected ?int $skipRecords = null,
        protected ?int $numberToRead = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?bool $expandAccountInfo = null,
        protected ?bool $expandBranchInfo = null,
        protected ?bool $includeTransactionBalance = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'branch' => $this->branch,
            'ledger' => $this->ledger,
            'fromPeriod' => $this->fromPeriod,
            'toPeriod' => $this->toPeriod,
            'account' => $this->account,
            'subaccountId' => $this->subaccountId,
            'fromDate' => $this->fromDate,
            'toDate' => $this->toDate,
            'includeUnposted' => $this->includeUnposted,
            'includeUnreleased' => $this->includeUnreleased,
            'skipRecords' => $this->skipRecords,
            'numberToRead' => $this->numberToRead,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'expandAccountInfo' => $this->expandAccountInfo,
            'expandBranchInfo' => $this->expandBranchInfo,
            'includeTransactionBalance' => $this->includeTransactionBalance,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
