<?php

namespace Pionect\VismaSdk\Requests\Account;

use Pionect\VismaSdk\Dto\AccountDto;
use Pionect\VismaSdk\Foundation\Hydration\Facades\Hydrator;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * Account_GetAll
 *
 * Data for Account
 */
class AccountGetAllCollectionRequest extends Request implements Paginatable
{
    protected $model = AccountDto::class;

    protected Method $method = Method::GET;

    public function createDtoFromResponse(Response $response): mixed
    {
        return Hydrator::hydrateCollection(
            $this->model,
            $response->json()
        );
    }

    public function resolveEndpoint(): string
    {
        return '/v1/account';
    }

    /**
     * @param  null|bool  $active  Set to True to select active accounts.
     * @param  null|bool  $includeAccountClassDescription  Set to True to include AccountClass description.
     * @param  null|string  $greaterThanValue  Enter the from-value for Account no.
     * @param  null|string  $publicCode  Filter by the Public code 1, authorities mapped code to the account.
     * @param  null|string  $externalCode1  Filter by External code 1 (field used for sorting and inquiries.)
     * @param  null|string  $externalCode2  Filter by External code 2 (field used for sorting and inquiries.)
     * @param  null|string  $analysisCode  Filter by Analysis code (field used for sorting and inquiries.)
     * @param  null|int  $numberToRead  This field has been deprecated and will be removed in future versions.
     * @param  null|int  $skipRecords  This field has been deprecated and will be removed in future versions.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?bool $active = null,
        protected ?bool $includeAccountClassDescription = null,
        protected ?string $greaterThanValue = null,
        protected ?string $publicCode = null,
        protected ?string $externalCode1 = null,
        protected ?string $externalCode2 = null,
        protected ?string $analysisCode = null,
        protected ?int $numberToRead = null,
        protected ?int $skipRecords = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'active' => $this->active,
            'includeAccountClassDescription' => $this->includeAccountClassDescription,
            'greaterThanValue' => $this->greaterThanValue,
            'publicCode' => $this->publicCode,
            'externalCode1' => $this->externalCode1,
            'externalCode2' => $this->externalCode2,
            'analysisCode' => $this->analysisCode,
            'numberToRead' => $this->numberToRead,
            'skipRecords' => $this->skipRecords,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
