<?php

namespace Pionect\VismaSdk\Enums;

/**
 * The top part > Status > The status of the document.
 */
enum ShipmentStatusEnum: string
{
    case OPEN = 'Open';
    case HOLD = 'Hold';
    case COMPLETED = 'Completed';
    case CANCELLED = 'Cancelled';
    case CONFIRMED = 'Confirmed';
    case INVOICED = 'Invoiced';
    case RECEIPTED = 'Receipted';
    case AUTO_GENERATED = 'AutoGenerated';
    case PARTIALLY_INVOICED = 'PartiallyInvoiced';
}
