<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

class AccountQueryParameters extends Model
{
    /** Set to True to select active accounts. */
    #[Property]
    public ?bool $active;

    /** Set to True to include AccountClass description. */
    #[Property]
    public ?bool $includeAccountClassDescription;

    /** Enter the from-value for Account no. */
    #[Property]
    public ?string $greaterThanValue;

    /** Filter by the Public code 1, authorities mapped code to the account. */
    #[Property]
    public ?string $publicCode;

    /** Filter by External code 1 (field used for sorting and inquiries.) */
    #[Property]
    public ?string $externalCode1;

    /** Filter by External code 2 (field used for sorting and inquiries.) */
    #[Property]
    public ?string $externalCode2;

    /** Filter by Analysis code (field used for sorting and inquiries.) */
    #[Property]
    public ?string $analysisCode;

    /** This field has been deprecated and will be removed in future versions. */
    #[Property]
    public ?int $numberToRead;

    /** This field has been deprecated and will be removed in future versions. */
    #[Property]
    public ?int $skipRecords;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;
}
