<?php

namespace Pionect\VismaSdk\Dto;

use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\AccountQueryParametersFactory testFactory()
 */
class AccountQueryParameters extends SpatieData
{
    /** @use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory<\Pionect\VismaSdk\Factories\AccountQueryParametersFactory> */
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /** Set to True to select active accounts. */
        public ?bool $active = null,
        /** Set to True to include AccountClass description. */
        public ?bool $includeAccountClassDescription = null,
        /** Enter the from-value for Account no. */
        public ?string $greaterThanValue = null,
        /** Filter by the Public code 1, authorities mapped code to the account. */
        public ?string $publicCode = null,
        /** Filter by External code 1 (field used for sorting and inquiries.) */
        public ?string $externalCode1 = null,
        /** Filter by External code 2 (field used for sorting and inquiries.) */
        public ?string $externalCode2 = null,
        /** Filter by Analysis code (field used for sorting and inquiries.) */
        public ?string $analysisCode = null,
        /** This field has been deprecated and will be removed in future versions. */
        public ?int $numberToRead = null,
        /** This field has been deprecated and will be removed in future versions. */
        public ?int $skipRecords = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
    ) {}
}
