<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * @extends \Pionect\VismaSdk\Foundation\Hydration\Model<\Pionect\VismaSdk\Factories\BranchQueryParametersFactory>
 *
 * @method static \Pionect\VismaSdk\Factories\BranchQueryParametersFactory factory()
 */
class BranchQueryParameters extends Model
{
    /** Filter by branch ID (number) greater than. */
    #[Property]
    public ?string $greaterThanValue;

    /** Order by Branch ID */
    #[Property]
    public ?string $orderBy;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /** True to get main address for branch. */
    #[Property]
    public ?bool $expandAddress;

    /** True to get main contact for a branch. */
    #[Property]
    public ?bool $expandContact;

    /** True to get base currency for a branch. */
    #[Property]
    public ?bool $expandCurrency;

    /** True to get vat zone for a branch. */
    #[Property]
    public ?bool $expandVatZone;

    /** True to get ledger for a branch. */
    #[Property]
    public ?bool $expandLedger;

    /** True to get industry code for a branch. */
    #[Property]
    public ?bool $expandIndustryCode;

    /** True to get delivery address for a branch. */
    #[Property]
    public ?bool $expandDeliveryAddress;

    /** True to get delivery contact for a branch. */
    #[Property]
    public ?bool $expandDeliveryContact;

    /** True to get default country for a branch. */
    #[Property]
    public ?bool $expandDefaultCountry;

    /** True to get payment settings for Branch. */
    #[Property]
    public ?bool $expandBankSettings;
}
