<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\BranchQueryParametersOrderByEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\BranchQueryParametersFactory testFactory()
 */
class BranchQueryParameters extends SpatieData
{
    /** @use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory<\Pionect\VismaSdk\Factories\BranchQueryParametersFactory> */
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /** Filter by branch ID (number) greater than. */
        public ?string $greaterThanValue = null,
        /** Order by Branch ID */
        public ?BranchQueryParametersOrderByEnum $orderBy = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?\Carbon\Carbon $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        /** True to get main address for branch. */
        public ?bool $expandAddress = null,
        /** True to get main contact for a branch. */
        public ?bool $expandContact = null,
        /** True to get base currency for a branch. */
        public ?bool $expandCurrency = null,
        /** True to get vat zone for a branch. */
        public ?bool $expandVatZone = null,
        /** True to get ledger for a branch. */
        public ?bool $expandLedger = null,
        /** True to get industry code for a branch. */
        public ?bool $expandIndustryCode = null,
        /** True to get delivery address for a branch. */
        public ?bool $expandDeliveryAddress = null,
        /** True to get delivery contact for a branch. */
        public ?bool $expandDeliveryContact = null,
        /** True to get default country for a branch. */
        public ?bool $expandDefaultCountry = null,
        /** True to get payment settings for Branch. */
        public ?bool $expandBankSettings = null,
    ) {}
}
