<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\CustomerStatusEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\CustomerQueryParametersFactory testFactory()
 */
class CustomerQueryParameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /**
         * This field does not work and has been deprecated. It will be removed in
         * future versions.
         */
        public ?string $greaterThanValue = null,
        /**
         * [This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.]
         * Tells the service to return only {numberToRead} number of records.
         */
        public ?int $numberToRead = null,
        /**
         * [This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.]
         * Tells the service to return only records after the first {skipRecords} number
         * of records.
         */
        public ?int $skipRecords = null,
        /** Equals Customer name. */
        public ?string $name = null,
        /** Drop down and select Status. */
        public ?CustomerStatusEnum $status = null,
        /** Equals Corporate ID from Delivery settings tab. */
        public ?string $corporateId = null,
        /** Equals VAT registration ID from Delivery settings tab. */
        public ?string $vatRegistrationId = null,
        /** Equals Email for customer. */
        public ?string $email = null,
        /** Equals Phone 1 for customer. */
        public ?string $phone = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        public ?string $createdDateTime = null,
        public ?string $createdDateTimeCondition = null,
        public ?bool $expandAccountInformation = null,
        public ?bool $expandPaymentMethods = null,
        /** Expand direct debit info */
        public ?bool $expandDirectDebit = null,
        /**
         * Attributes (additional information) connected to the entity.
         *  Examples:
         * {{base}}/customer?attributes={"AttributeID":"ValueID","AttributeID":"ValueID"}
         * {{base}}/customer?attributes={"AttributeID":"ValueID1,ValueID2"}
         */
        public ?string $attributes = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
