<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * @extends \Pionect\VismaSdk\Foundation\Hydration\Model<\Pionect\VismaSdk\Factories\CustomerQueryParametersFactory>
 *
 * @method static \Pionect\VismaSdk\Factories\CustomerQueryParametersFactory factory()
 */
class CustomerQueryParameters extends Model
{
    /** This field does not work and has been deprecated. It will be removed in future versions. */
    #[Property]
    public ?string $greaterThanValue;

    /**
     * [This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.]
     * Tells the service to return only {numberToRead} number of records.
     */
    #[Property]
    public ?int $numberToRead;

    /**
     * [This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.]
     * Tells the service to return only records after the first {skipRecords} number of records.
     */
    #[Property]
    public ?int $skipRecords;

    /** Equals Customer name. */
    #[Property]
    public ?string $name;

    /** Drop down and select Status. */
    #[Property]
    public ?string $status;

    /** Equals Corporate ID from Delivery settings tab. */
    #[Property]
    public ?string $corporateId;

    /** Equals VAT registration ID from Delivery settings tab. */
    #[Property]
    public ?string $vatRegistrationId;

    /** Equals Email for customer. */
    #[Property]
    public ?string $email;

    /** Equals Phone 1 for customer. */
    #[Property]
    public ?string $phone;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $createdDateTime;

    #[Property]
    public ?string $createdDateTimeCondition;

    #[Property]
    public ?bool $expandAccountInformation;

    #[Property]
    public ?bool $expandPaymentMethods;

    /** Expand direct debit info */
    #[Property]
    public ?bool $expandDirectDebit;

    /**
     * Attributes (additional information) connected to the entity.
     *  Examples:
     * {{base}}/customer?attributes={"AttributeID":"ValueID","AttributeID":"ValueID"}
     * {{base}}/customer?attributes={"AttributeID":"ValueID1,ValueID2"}
     */
    #[Property]
    public ?string $attributes;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;

    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     */
    #[Property]
    public ?int $pageSize;
}
