<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\CashSaleDocumentTypeEnum;
use Pionect\VismaSdk\Enums\CashSaleStatusEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\DocumentQueryParametersFactory testFactory()
 */
class DocumentQueryParameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /**
         * The field is deprecated for specific customer document endpoints. It will
         * only be usable from customer document endpoint.
         */
        public ?CashSaleDocumentTypeEnum $documentType = null,
        /** Parameter for showing if invoice has been released or not. */
        public ?int $released = null,
        /** The dunning level of the document. */
        public ?int $dunningLevel = null,
        /** The date of the closing of the financial period. */
        public ?string $closedFinancialPeriod = null,
        /** The date and time for when the document last released a dunning letter. */
        public ?string $dunningLetterDateTime = null,
        /**
         * Set time/date as before (<), after (>), before and including (=<) OR after
         * and including (=>) to filter on time frame.
         */
        public ?string $dunningLetterDateTimeCondition = null,
        /** The project with which the document is associated. */
        public ?string $project = null,
        /** True if you want to see all dunning information regarding this document. */
        public ?bool $expandApplications = null,
        public ?bool $expandDunningInformation = null,
        /** True if you want to see all attachments regarding this document. */
        public ?bool $expandAttachments = null,
        /** True if you want to see all VAT details regarding this document. */
        public ?bool $expandTaxDetails = null,
        /**
         * True if you want to see all information regarding the invoice address for
         * this document.
         */
        public ?bool $expandInvoiceAddress = null,
        /**
         * The financial period to which the transactions recorded in the document is
         * posted. Format YYYYMM.
         */
        public ?string $financialPeriod = null,
        /**
         * The date when payment for the document is due, in accordance with the credit
         * terms.
         */
        public ?\Carbon\Carbon $documentDueDate = null,
        /**
         * This value represents the condition to be applied to the Due Date when
         * retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         */
        public ?string $documentDueDateCondition = null,
        /** The status of the document. Use the dropdown to select status. */
        public ?CashSaleStatusEnum $status = null,
        /**
         * This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.
         */
        public ?int $numberToRead = null,
        /**
         * This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.
         */
        public ?int $skipRecords = null,
        /**
         * The top part > External reference > The external reference used in
         * AutoInvoice.
         */
        public ?string $externalReference = null,
        /**
         * The top part > Payment ref. > The reference number of the document, as
         * automatically generated by the system in accordance with the number series
         * assigned to cash sales in the Customer ledger preferences window..
         */
        public ?string $paymentReference = null,
        /**
         * The top part > External reference > The external reference used in
         * AutoInvoice.
         */
        public ?string $customerRefNumber = null,
        /** Filter by Customer */
        public ?string $customer = null,
        /** Filter by Branch */
        public ?string $branch = null,
        /**
         * This value indicates the document date. Use it to retrieve all records that
         * have the Document Date since that time, up to the future.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         *
         * _Note:_ __DocumentDate__ and __DocumentDateCondition__ are __mutually
         * inclusive__.
         */
        public ?\Carbon\Carbon $documentDate = null,
        /**
         * This value represents the condition to be applied to the Document Date when
         * retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __DocumentDate__ and __DocumentDateCondition__ are __mutually
         * inclusive__.
         */
        public ?string $documentDateCondition = null,
        /**
         * Greater than value. The item which is the object for this, varies from API to
         * API.
         */
        public ?string $greaterThanValue = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        /** Creation date and time. */
        public ?string $createdDateTime = null,
        /** System-retrieved information for state/condition */
        public ?string $createdDateTimeCondition = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
