<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

class DocumentQueryParameters extends Model
{
    /** The field is deprecated for specific customer document endpoints. It will only be usable from customer document endpoint. */
    #[Property]
    public ?string $documentType;

    /** Parameter for showing if invoice has been released or not. */
    #[Property]
    public ?int $released;

    /** The dunning level of the document. */
    #[Property]
    public ?int $dunningLevel;

    /** The date of the closing of the financial period. */
    #[Property]
    public ?string $closedFinancialPeriod;

    /** The date and time for when the document last released a dunning letter. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $dunningLetterDateTime;

    /** Set time/date as before (&lt;), after (&gt;), before and including (=&lt;) OR after and including (=&gt;) to filter on time frame. */
    #[Property]
    public ?string $dunningLetterDateTimeCondition;

    /** The project with which the document is associated. */
    #[Property]
    public ?string $project;

    /** True if you want to see all dunning information regarding this document. */
    #[Property]
    public ?bool $expandApplications;

    #[Property]
    public ?bool $expandDunningInformation;

    /** True if you want to see all attachments regarding this document. */
    #[Property]
    public ?bool $expandAttachments;

    /** True if you want to see all VAT details regarding this document. */
    #[Property]
    public ?bool $expandTaxDetails;

    /** True if you want to see all information regarding the invoice address for this document. */
    #[Property]
    public ?bool $expandInvoiceAddress;

    /** The financial period to which the transactions recorded in the document is posted. Format YYYYMM. */
    #[Property]
    public ?string $financialPeriod;

    /** The date when payment for the document is due, in accordance with the credit terms. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $documentDueDate;

    /**
     * This value represents the condition to be applied to the Due Date when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     */
    #[Property]
    public ?string $documentDueDateCondition;

    /** The status of the document. Use the dropdown to select status. */
    #[Property]
    public ?string $status;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $numberToRead;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $skipRecords;

    /** The top part &gt; External reference &gt; The external reference used in AutoInvoice. */
    #[Property]
    public ?string $externalReference;

    /** The top part &gt; Payment ref. &gt; The reference number of the document, as automatically generated by the system in accordance with the number series assigned to cash sales in the Customer ledger preferences window.. */
    #[Property]
    public ?string $paymentReference;

    /** The top part &gt; External reference &gt; The external reference used in AutoInvoice. */
    #[Property]
    public ?string $customerRefNumber;

    /** Filter by Customer */
    #[Property]
    public ?string $customer;

    /** Filter by Branch */
    #[Property]
    public ?string $branch;

    /**
     * This value indicates the document date. Use it to retrieve all records that have the Document Date since that time, up to the future.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     *
     * _Note:_ __DocumentDate__ and __DocumentDateCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $documentDate;

    /**
     * This value represents the condition to be applied to the Document Date when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __DocumentDate__ and __DocumentDateCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $documentDateCondition;

    /** Greater than value. The item which is the object for this, varies from API to API. */
    #[Property]
    public ?string $greaterThanValue;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /** Creation date and time. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $createdDateTime;

    /** System-retrieved information for state/condition */
    #[Property]
    public ?string $createdDateTimeCondition;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;

    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     */
    #[Property]
    public ?int $pageSize;
}
