<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\FixedAssetRegisterStatusEnum;
use Pionect\VismaSdk\Enums\FixedAssetTransactionTransactionTypeEnum;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\FixedAssetTransactionQueryParametersFactory testFactory()
 */
class FixedAssetTransactionQueryParameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /** View all transactions connected to this Reference number. */
        public ?string $refNo = null,
        /** View all transactions connected to this Asset ID. */
        #[MapName('assetID')]
        public ?string $assetId = null,
        /** View all transactions in this Book ID. */
        #[MapName('bookID')]
        public ?string $bookId = null,
        /** View all transactions from and including this Period. Format: YYYYMM. */
        public ?string $fromPeriod = null,
        /** View all transactions to and including this Period. Format: YYYYMM. */
        public ?string $toPeriod = null,
        /** View all transactions for this Account ID. */
        #[MapName('accountID')]
        public ?string $accountId = null,
        /** View all transactions for this Sub Account ID. */
        #[MapName('subAccountID')]
        public ?string $subAccountId = null,
        /**
         * View all transactions with this Status. Available statuses: Balanced, OnHold,
         * Posted and UnPosted.
         */
        public ?FixedAssetRegisterStatusEnum $status = null,
        /**
         * View all transactions with this Transaction Type. Available types:
         * PurchasingPlus, PurchasingMinus, DepreciationPlus, DepreciationMinus,
         * CalculatedPlus, CalculatedMinu,SalePlus, SaleMinus,TransferPurchasing,
         * TransferDepreciation, ReconciliationPlus, ReconciliationMinus,
         * PurchasingDisposal, PurchasingReversal, AdjustingDeprPlus and
         * AdjustingDeprMinus.
         */
        public ?FixedAssetTransactionTransactionTypeEnum $transactionType = null,
        /**
         * View all transactions from and including this Transaction Date. Date format:
         * YYYY-MM-DD.
         */
        public ?string $transactionFromDate = null,
        /**
         * View all transactions to and including this Transaction Date inclusive. Date
         * format: YYYY-MM-DD .
         */
        public ?string $transactionToDate = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
