<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * @extends \Pionect\VismaSdk\Foundation\Hydration\Model<\Pionect\VismaSdk\Factories\FixedAssetTransactionQueryParametersFactory>
 *
 * @method static \Pionect\VismaSdk\Factories\FixedAssetTransactionQueryParametersFactory factory()
 */
class FixedAssetTransactionQueryParameters extends Model
{
    /** View all transactions connected to this Reference number. */
    #[Property]
    public ?string $refNo;

    /** View all transactions connected to this Asset ID. */
    #[Property]
    public ?string $assetId;

    /** View all transactions in this Book ID. */
    #[Property]
    public ?string $bookId;

    /** View all transactions from and including this Period. Format: YYYYMM. */
    #[Property]
    public ?string $fromPeriod;

    /** View all transactions to and including this Period. Format: YYYYMM. */
    #[Property]
    public ?string $toPeriod;

    /** View all transactions for this Account ID. */
    #[Property]
    public ?string $accountId;

    /** View all transactions for this Sub Account ID. */
    #[Property]
    public ?string $subAccountId;

    /** View all transactions with this Status. Available statuses: Balanced, OnHold, Posted and UnPosted. */
    #[Property]
    public ?string $status;

    /** View all transactions with this Transaction Type. Available types: PurchasingPlus, PurchasingMinus, DepreciationPlus, DepreciationMinus, CalculatedPlus, CalculatedMinu,SalePlus, SaleMinus,TransferPurchasing, TransferDepreciation, ReconciliationPlus, ReconciliationMinus, PurchasingDisposal, PurchasingReversal, AdjustingDeprPlus and AdjustingDeprMinus. */
    #[Property]
    public ?string $transactionType;

    /** View all transactions from and including this Transaction Date. Date format: YYYY-MM-DD. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $transactionFromDate;

    /** View all transactions to and including this Transaction Date inclusive. Date format: YYYY-MM-DD . */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $transactionToDate;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;

    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     */
    #[Property]
    public ?int $pageSize;
}
