<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\DetailsStatusEnum;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\FixedAssetQueryParametersFactory testFactory()
 */
class FixedAssetQueryParameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /** Fixed Asset ID that identifies the asset. */
        #[MapName('assetID')]
        public ?string $assetId = null,
        /** View all fixed assets with this Fixed Asset Class ID. */
        #[MapName('classID')]
        public ?string $classId = null,
        /**
         * View all fixed assets with this Status. Available statuses are: Active,
         * Disposed, FullyDepriciated, Hold, Reversed, Suspended.
         */
        public ?DetailsStatusEnum $status = null,
        /** From 'Placed in service date' inclusive. Date format: YYYY-MM-DD. */
        public ?\Carbon\Carbon $fromDate = null,
        /** To 'Placed in service date' inclusive. Date format: YYYY-MM-DD. */
        public ?\Carbon\Carbon $toDate = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        /** Set to True to include accounts and subaccounts. Default value is False */
        public ?bool $expandAccounts = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
