<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

class FixedAssetQueryParameters extends Model
{
    /** Fixed Asset ID that identifies the asset. */
    #[Property]
    public ?string $assetId;

    /** View all fixed assets with this Fixed Asset Class ID. */
    #[Property]
    public ?string $classId;

    /** View all fixed assets with this Status. Available statuses are: Active, Disposed, FullyDepriciated, Hold, Reversed, Suspended. */
    #[Property]
    public ?string $status;

    /** From 'Placed in service date' inclusive. Date format: YYYY-MM-DD. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $fromDate;

    /** To 'Placed in service date' inclusive. Date format: YYYY-MM-DD. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $toDate;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /** Set to True to include accounts and subaccounts. Default value is False */
    #[Property]
    public ?bool $expandAccounts;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;

    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     */
    #[Property]
    public ?int $pageSize;
}
