<?php

namespace Pionect\VismaSdk\Dto;

use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\GeneralLedgerTransactionsQueryParametersFactory testFactory()
 */
class GeneralLedgerTransactionsQueryParameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /** The branch CD */
        public ?string $branch = null,
        /** Mandatory. The ledger in which you want to view the account balances. */
        public ?string $ledger = null,
        /**
         * The financial period that begins the date range of the batches you want to
         * view. Format YYYYPP
         */
        public ?string $fromPeriod = null,
        /**
         * The financial period that ends the date range of the batches you want to
         * view. Format YYYYPP
         */
        public ?string $toPeriod = null,
        /**
         * The account CD for which you want to view activities in the selected
         * financial period.
         */
        public ?string $account = null,
        /** The Subaccount */
        public ?string $subaccountId = null,
        /** The first date of the interval within the period. Format YYYY-MM-DD */
        public ?string $fromDate = null,
        /** The last date of the interval within the selected period. Format YYYY-MM-DD */
        public ?string $toDate = null,
        /** Checkmark indicating if unposted batches are included. */
        public ?bool $includeUnposted = null,
        /** Checkmark indicating if unreleased (balanced) batches are included. */
        public ?bool $includeUnreleased = null,
        /**
         * This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.
         */
        public ?int $skipRecords = null,
        /**
         * This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.
         */
        public ?int $numberToRead = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        /**
         * By default, if no value is provided, False and the account information will
         * include only Number, Description, Type and GlConsolAccountCD.
         * If True, each transaction returned will include extended information about
         * account.
         */
        public ?bool $expandAccountInfo = null,
        /**
         * By default, if no value is provided, False and branch information will
         * include only branch number.
         * If True, each transaction returned will include extended information about
         * Branch (number and name).
         */
        public ?bool $expandBranchInfo = null,
        /**
         * By default, if no value is provided, False and the transactions returned will
         * not include their balances (fields BegBalance, EndingBalance, CurrBegBalance,
         * CurrEndingBalance)
         * If True, each transaction returned will include its balance.
         */
        public ?bool $includeTransactionBalance = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
