<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

class GeneralLedgerTransactionsQueryParameters extends Model
{
    /** The branch CD */
    #[Property]
    public ?string $branch;

    /** Mandatory. The ledger in which you want to view the account balances. */
    #[Property]
    public ?string $ledger;

    /** The financial period that begins the date range of the batches you want to view. Format YYYYPP */
    #[Property]
    public ?string $fromPeriod;

    /** The financial period that ends the date range of the batches you want to view. Format YYYYPP */
    #[Property]
    public ?string $toPeriod;

    /** The account CD for which you want to view activities in the selected financial period. */
    #[Property]
    public ?string $account;

    /** The Subaccount */
    #[Property]
    public ?string $subaccountId;

    /** The first date of the interval within the period. Format YYYY-MM-DD */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $fromDate;

    /** The last date of the interval within the selected period. Format YYYY-MM-DD */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $toDate;

    /** Checkmark indicating if unposted batches are included. */
    #[Property]
    public ?bool $includeUnposted;

    /** Checkmark indicating if unreleased (balanced) batches are included. */
    #[Property]
    public ?bool $includeUnreleased;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $skipRecords;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $numberToRead;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /**
     * By default, if no value is provided, False and the account information will include only Number, Description, Type and GlConsolAccountCD.
     * If True, each transaction returned will include extended information about account.
     */
    #[Property]
    public ?bool $expandAccountInfo;

    /**
     * By default, if no value is provided, False and branch information will include only branch number.
     * If True, each transaction returned will include extended information about Branch (number and name).
     */
    #[Property]
    public ?bool $expandBranchInfo;

    /**
     * By default, if no value is provided, False and the transactions returned will not include their balances (fields BegBalance, EndingBalance, CurrBegBalance, CurrEndingBalance)
     * If True, each transaction returned will include its balance.
     */
    #[Property]
    public ?bool $includeTransactionBalance;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;

    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     */
    #[Property]
    public ?int $pageSize;
}
