<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\GeneralLedgerPeriodBalanceQueryParametersBalanceTypeEnum;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\GeneralLedgerPeriodBalanceQueryParametersFactory testFactory()
 */
class GeneralLedgerPeriodBalanceQueryParameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /**
         * Period to retrieve balance for. Mandatory if 'LastModifiedDateTime' not
         * provided. Format: 'yyyyMM'
         */
        public ?string $periodId = null,
        /** Account to retrieve balance for */
        public ?string $account = null,
        /** Ledger to retrieve balance for */
        public ?string $ledger = null,
        /** Branch to retrieve balance for */
        public ?string $branch = null,
        /** Balance Type of the ledger to be exported */
        public ?GeneralLedgerPeriodBalanceQueryParametersBalanceTypeEnum $balanceType = null,
        /**
         * Parameter can be used in order to change the balance sign for liability and
         * income accounts
         */
        public ?bool $toggleBalanceSigns = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         * Mandatory if 'PeriodId' is not provided.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         */
        public ?\Carbon\Carbon $lastModifiedDateTime = null,
        #[MapName('excludeYTDAccount')]
        public ?bool $excludeYtdaccount = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
