<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * @extends \Pionect\VismaSdk\Foundation\Hydration\Model<\Pionect\VismaSdk\Factories\GeneralLedgerBudgetQueryParametersFactory>
 *
 * @method static \Pionect\VismaSdk\Factories\GeneralLedgerBudgetQueryParametersFactory factory()
 */
class GeneralLedgerBudgetQueryParameters extends Model
{
    /** True to get released budgets. */
    #[Property]
    public ?bool $isReleased;

    /** Filter by from date. */
    #[Property]
    public ?string $greaterThanValue;

    /** This field has been deprecated and will be removed in future versions. */
    #[Property]
    public ?int $numberToRead;

    /** This field has been deprecated and will be removed in future versions. */
    #[Property]
    public ?int $skipRecords;

    /** Order by Last modified date and time. */
    #[Property]
    public ?string $orderBy;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /** Mandatory. Filter by budgets Branch. */
    #[Property]
    public ?string $branch;

    /** Mandatory. The budgets Ledger */
    #[Property]
    public ?string $ledger;

    /** The budgets financial year. */
    #[Property]
    public ?string $financialYear;

    /** The Subaccount of the budget article. */
    #[Property]
    public ?string $subaccount;
}
