<?php

namespace Pionect\VismaSdk\Dto;

use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\GeneralLedgerBudgetQueryParametersFactory testFactory()
 */
class GeneralLedgerBudgetQueryParameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /** True to get released budgets. */
        public ?bool $isReleased = null,
        /** Filter by from date. */
        public ?string $greaterThanValue = null,
        /** This field has been deprecated and will be removed in future versions. */
        public ?int $numberToRead = null,
        /** This field has been deprecated and will be removed in future versions. */
        public ?int $skipRecords = null,
        /** Order by Last modified date and time. */
        public ?string $orderBy = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        /** Mandatory. Filter by budgets Branch. */
        public ?string $branch = null,
        /** Mandatory. The budgets Ledger */
        public ?string $ledger = null,
        /** The budgets financial year. */
        public ?string $financialYear = null,
        /** The Subaccount of the budget article. */
        public ?string $subaccount = null,
    ) {}
}
