<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

class GeneralLedgerPeriodBalanceQueryParameters extends Model
{
    /** Period to retrieve balance for. Mandatory if 'LastModifiedDateTime' not provided. Format: 'yyyyMM' */
    #[Property]
    public ?string $periodId;

    /** Account to retrieve balance for */
    #[Property]
    public ?string $account;

    /** Ledger to retrieve balance for */
    #[Property]
    public ?string $ledger;

    /** Branch to retrieve balance for */
    #[Property]
    public ?string $branch;

    /** Balance Type of the ledger to be exported */
    #[Property]
    public ?string $balanceType;

    /** Parameter can be used in order to change the balance sign for liability and income accounts */
    #[Property]
    public ?bool $toggleBalanceSigns;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     * Mandatory if 'PeriodId' is not provided.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    #[Property]
    public ?bool $excludeYtdaccount;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;

    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     */
    #[Property]
    public ?int $pageSize;
}
