<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * @extends \Pionect\VismaSdk\Foundation\Hydration\Model<\Pionect\VismaSdk\Factories\InventoryQueryParametersFactory>
 *
 * @method static \Pionect\VismaSdk\Factories\InventoryQueryParametersFactory factory()
 */
class InventoryQueryParameters extends Model
{
    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     * MaxPageSize will be set to 5000 from 1. April 2022
     */
    #[Property]
    public ?int $pageSize;

    /** Applies for both Stock and Non-stock items.  Some fields in this filter applies only for one of these. */
    #[Property]
    public ?string $alternateId;

    /** The Item ID. */
    #[Property]
    public ?string $inventoryNumber;

    /** The Category ID for the sales category, found on the Attributes tab. */
    #[Property]
    public ?int $salesCategory;

    /** This filter can be used only for stock items, from the Price/cost information tab. */
    #[Property]
    public ?bool $addCostPriceStatistics;

    /**
     * Attributes (additional information) connected to the entity.
     *  Examples:
     * {{base}}/inventory?attributes={"AttributeID":"ValueID","AttributeID":"ValueID"}
     * {{base}}/inventory?attributes={"AttributeID":"ValueID1,ValueID2"}
     */
    #[Property]
    public ?string $attributes;

    /** A brief description of the stock item from the Top part of the window. */
    #[Property]
    public ?string $description;

    /** System retrieved information. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $availabilityLastModifiedDateTime;

    /** System retrieved information for state/condition. */
    #[Property]
    public ?string $availabilityLastModifiedDateTimeCondition;

    /** Filter on one or more inventory types: NonStockItem, LaborItem, ServiceItem, ChargeItem, ExpenseItem, FinishedGoodItem, ComponentPartItem or SubassemblyItem */
    #[Property]
    public ?array $inventoryTypes;

    /**
     * These expand fields are by default set to true, but will be changed in the future.
     * Set to true to retrieve information about the cross-references (item ID and suppliers/customers ID for the item connected to the item.
     */
    #[Property]
    public ?bool $expandCrossReference;

    /** Set to true to retrieve information about the attachments connected to the item. */
    #[Property]
    public ?bool $expandAttachment;

    /** Set to true to retrieve the attribute descriptions used for the item. */
    #[Property]
    public ?bool $expandAttribute;

    /** Set to true to retrieve information about the warehouse connected to the item. */
    #[Property]
    public ?bool $expandWarehouseDetail;

    /** Set to true to retrieve information about the account information connected to the item. */
    #[Property]
    public ?bool $expandAccountInformation;

    /** Set to true to retrieve information about the units of measure connected to the item. */
    #[Property]
    public ?bool $expandInventoryUnits;

    /** Set to true to retrieve details about the supplier connected to the item. */
    #[Property]
    public ?bool $expandSupplierDetails;

    /** Set to true to retrieve details about the sales categories connected to the item. */
    #[Property]
    public ?bool $expandSalesCategories;

    /** Set to true to retrieve the note value connected to the item. */
    #[Property]
    public ?bool $expandNote;

    /** System retrieved information for last modified date and time for attachment. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $attachmentLastModifiedDateTime;

    /** System retrieved information for state/condition for attachment. */
    #[Property]
    public ?string $attachmentLastModifiedDateTimeCondition;

    /** The inventory item status */
    #[Property]
    public ?string $status;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $numberToRead;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $skipRecords;

    /** Greater than value. The item which is the object for this, varies from API to API. */
    #[Property]
    public ?string $greaterThanValue;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /** Creation date and time. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $createdDateTime;

    /** System-retrieved information for state/condition */
    #[Property]
    public ?string $createdDateTimeCondition;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;
}
