<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\JournalTransactionLineModuleEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\JournalTransactionLineDtoFactory testFactory()
 */
class JournalTransactionLineDto extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /** Number at the left indicating the line number of the table. */
        public ?int $lineNumber = null,
        /**
         * Mandatory field: The table > Account* > The account (associated with the
         * specified branch) whose balance will be updated by the journal entry.
         */
        public ?string $accountNumber = null,
        /**
         * Description > A detailed description provided by a user or generated by the
         * system.
         */
        public ?string $description = null,
        public ?SubaccountInJournalTransactionLineDto $subaccount = null,
        /**
         * Ref. no. > The reference number of the external or internal document
         * associated with the journal transaction.
         */
        public ?string $referenceNumber = null,
        /** Debit amount > The debit amount of the journal entry. */
        public int|float|null $debitAmount = null,
        /**
         * Background calculation giving you the debit amount in your default currency.
         * This field is applicable if the amount is given in another currency than your
         * default.
         */
        public int|float|null $debitAmountInCurrency = null,
        /** Credit amount > The credit amount of the journal entry. */
        public int|float|null $creditAmount = null,
        /**
         * Background calculation giving you the Credit amount in your default currency.
         * This field is applicable if the amount is given in another currency than your
         * default.
         */
        public int|float|null $creditAmountInCurrency = null,
        /**
         * Transaction Description > A description of the transaction or any comments
         * relevant to the transaction.
         */
        public ?string $transactionDescription = null,
        public ?VatCodeInJournalTransactionLineDto $vatCode = null,
        public ?VatInJournalTransactionLineDto $vat = null,
        /** Branch > The branch associated with this journal entry. */
        public ?string $branch = null,
        /** Customer/Supplier > The customer or supplier associated with the entry. */
        public ?string $customerSupplier = null,
        /**
         * The top part > Type > The type of this general ledger batch, which is
         * specified by the system automatically.
         */
        public ?string $transactionType = null,
        /**
         * The workspace where the batch originates. See module in the Top part >
         * Workspace
         */
        public ?JournalTransactionLineModuleEnum $module = null,
        /** UoM > The quantity of items associated with the transaction, if relevant. */
        public ?string $uom = null,
        public ?ProjectInJournalTransactionLineDto $project = null,
        public ?ProjectTaskInJournalTransactionLineDto $projectTask = null,
        /** @var AttachmentDto[]|null */
        public ?array $attachments = null,
        /**
         * Quantity > The quantity of items associated with the transaction, if
         * relevant.
         */
        public int|float|null $quantity = null,
        /** Item ID > The item ID of the line item, if applicable. */
        public ?string $inventoryNumber = null,
        public ?string $note = null,
    ) {}
}
