<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\JournalTransactionQueryV2parametersStatusEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\JournalTransactionQueryV2parametersFactory testFactory()
 */
class JournalTransactionQueryV2parameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /**
         * Financial Period to query data for. Mandatory if 'LastModifiedDateTime' not
         * provided. Format: YYYYPP
         */
        public ?string $periodId = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         * Mandatory if 'PeriodId' is not provided.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         */
        public ?string $lastModifiedDateTime = null,
        /** Module to query data for. Allowed values: GL, AP, AR, CM, CA, IN, DR, FA, PM */
        public ?string $module = null,
        /**
         * Journal transaction status to query data for. Available statuses : Hold,
         * Balanced, Unposted, Posted, Voided, Scheduled, Unreleased.
         */
        public ?JournalTransactionQueryV2parametersStatusEnum $status = null,
        /** If true, includes all attachments for batch. Default is false. */
        public ?bool $expandAttachments = null,
        /** Branch to query data for. */
        public ?string $branch = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
