<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

class JournalTransactionLineDto extends Model
{
    /** The table &gt; Number at the left indicating the line number of the table. */
    #[Property]
    public ?int $lineNumber;

    /** Mandatory field: The table &gt; Account* &gt; The account (associated with the specified branch) whose balance will be updated by the journal entry. */
    #[Property]
    public ?string $accountNumber;

    /** The table &gt; Description &gt; A detailed description provided by a user or generated by the system. */
    #[Property]
    public ?string $description;

    #[Property]
    public ?subaccountInJournalTransactionLineDto $subaccount;

    /** The table &gt; Ref. no. &gt; The reference number of the external or internal document associated with the journal transaction. */
    #[Property]
    public ?string $referenceNumber;

    /** The table &gt; Debit amount &gt; The debit amount of the journal entry. */
    #[Property]
    public ?float $debitAmount;

    /** Background calculation giving you the debit amount in your default currency. This field is applicable if the amount is given in another currency than your default. */
    #[Property]
    public ?float $debitAmountInCurrency;

    /** The table &gt; Credit amount &gt; The credit amount of the journal entry. */
    #[Property]
    public ?float $creditAmount;

    /** Background calculation giving you the Credit amount in your default currency. This field is applicable if the amount is given in another currency than your default. */
    #[Property]
    public ?float $creditAmountInCurrency;

    /** The table &gt; Transaction Description &gt; A description of the transaction or any comments relevant to the transaction. */
    #[Property]
    public ?string $transactionDescription;

    #[Property]
    public ?vatCodeInJournalTransactionLineDto $vatCode;

    #[Property]
    public ?vatInJournalTransactionLineDto $vat;

    /** The table &gt; Branch &gt; The branch associated with this journal entry. */
    #[Property]
    public ?string $branch;

    /** The table &gt; Customer/Supplier &gt; The customer or supplier associated with the entry. */
    #[Property]
    public ?string $customerSupplier;

    /** The top part &gt; Type &gt; The type of this general ledger batch, which is specified by the system automatically. */
    #[Property]
    public ?string $transactionType;

    /** The workspace where the batch originates. See module in the Top part &gt; Workspace */
    #[Property]
    public ?string $module;

    /** The table &gt; UoM &gt; The quantity of items associated with the transaction, if relevant. */
    #[Property]
    public ?string $uom;

    #[Property]
    public ?projectInJournalTransactionLineDto $project;

    #[Property]
    public ?projectTaskInJournalTransactionLineDto $projectTask;

    #[Property]
    public ?array $attachments;

    /** The table &gt; Quantity &gt; The quantity of items associated with the transaction, if relevant. */
    #[Property]
    public ?float $quantity;

    /** Item ID &gt; The item ID of the line item, if applicable. */
    #[Property]
    public ?string $inventoryNumber;

    #[Property]
    public ?string $note;
}
