<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

class JournalTransactionQueryV2parameters extends Model
{
    /** Financial Period to query data for. Mandatory if 'LastModifiedDateTime' not provided. Format: YYYYPP */
    #[Property]
    public ?string $periodId;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     * Mandatory if 'PeriodId' is not provided.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /** Module to query data for. Allowed values: GL, AP, AR, CM, CA, IN, DR, FA, PM */
    #[Property]
    public ?string $module;

    /** Journal transaction status to query data for. Available statuses : Hold, Balanced, Unposted, Posted, Voided, Scheduled, Unreleased. */
    #[Property]
    public ?string $status;

    /** If true, includes all attachments for batch. Default is false. */
    #[Property]
    public ?bool $expandAttachments;

    /** Branch to query data for. */
    #[Property]
    public ?string $branch;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;

    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     */
    #[Property]
    public ?int $pageSize;
}
