<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * This class represents a journal transaction in JournalTransactionController. Used by getting data.
 *
 * @extends \Pionect\VismaSdk\Foundation\Hydration\Model<\Pionect\VismaSdk\Factories\JournalTransactionDtoFactory>
 *
 * @method static \Pionect\VismaSdk\Factories\JournalTransactionDtoFactory factory()
 */
class JournalTransactionDto extends Model
{
    /** The top part &gt; Workspace &gt; The workspace where the batch originates. New batches can be created only for General ledger. */
    #[Property]
    public ?string $module;

    /** The top part &gt; Batch number &gt; The unique ID of the batch, which is generated by the numbering sequence assigned to batches in the GL102000 window. */
    #[Property]
    public ?string $batchNumber;

    /** The top part &gt; Status &gt; The current status of the batch. The status defines what processing can be applied to the batch. The following options are available: On hold, Balanced, Scheduled, Unposted, Posted, Void. */
    #[Property]
    public ?string $status;

    /** The top part &gt; Hold &gt; A check box that indicates (if selected) that the batch has the On hold status and cannot be released or posted. You can clear the check box only if the batch has total debits equal to total credits. */
    #[Property]
    public ?bool $hold;

    /** Mandatory field: The top part &gt; Transaction date* &gt; The date when the batch was created, which relates to the transaction dates of the journal entries. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $transactionDate;

    /** Mandatory field: The top part &gt; Post period* &gt; The financial period to which the transactions recorded in the document should be posted. Format MMYYYY. */
    #[Property]
    public ?string $postPeriod;

    /** Mandatory field: The top part Post period* &gt; The financial period to which the transactions should be posted. Format YYYYMM. */
    #[Property]
    public ?string $financialPeriod;

    /** Mandatory field: The top part &gt; Ledger* &gt; The unique ID of the ledger to which batch transactions are posted. By default, it is the default posting ledger specified for the branch in the GL101010 window, but another posting ledger can be selected. */
    #[Property]
    public ?string $ledger;

    /** Mandatory field: The top part &gt; Ledger* &gt; Click the magnifier &gt; The description of the ledger to which batch transactions are posted. By default, it is the default posting ledger specified for the branch in the GL101010 window, but another posting ledger can be selected. */
    #[Property]
    public ?string $ledgerDescription;

    /** The top part &gt; Currency &gt; The currency used for all the journal transactions in the selected batch. */
    #[Property]
    public ?string $currencyId;

    /** Ingformation collected from the system to calculate currency amount. */
    #[Property]
    public ?float $exchangeRate;

    /** The top part &gt; Automatic reversing &gt; A check box that indicates (if selected) that the batch is auto-reversing. */
    #[Property]
    public ?bool $autoReversing;

    /** The top part &gt; Reversing entry &gt; A check box that indicates (if selected) that the batch is a reversing batch. The Orig.batch number field displays the ID of the batch that was reversed by this batch. */
    #[Property]
    public ?bool $reversingEntry;

    /** The top part &gt; Description &gt; A description of the batch. */
    #[Property]
    public ?string $description;

    /** The top part &gt; Orig. batch number &gt; For a scheduled or auto-reversing batch, the reference number of the batch used as a template. */
    #[Property]
    public ?string $originalBatchNumber;

    /** The top part &gt; Debit total &gt; The total of transaction debit amounts for the batch; the value is calculated automatically. */
    #[Property]
    public ?float $debitTotal;

    /** Background calculation giving you the Debit total in your default currency. This field is applicable if the amount is given in another currency than your default. */
    #[Property]
    public ?float $debitTotalInCurrency;

    /** The top part &gt; Credit total &gt; The total of transaction credit amounts for the batch; the value is calculated automatically. */
    #[Property]
    public ?float $creditTotal;

    /** Background calculation giving you the Credit total in your default currency. This field is applicable if the amount is given in a another currency than your default. */
    #[Property]
    public ?float $creditTotalInCurrency;

    /** The top part &gt; Control total &gt; The control total of the batch, which is used for batch status validation. */
    #[Property]
    public ?float $controlTotal;

    /** Background calculation giving you the Control total in your default currency. This field is applicable if the amount is given in another currency than your default. */
    #[Property]
    public ?float $controlTotalInCurrency;

    /** The top part &gt; Create VAT transactions &gt; A check box that indicates (if selected) that a VAT-related transaction can be created manually; select this check box when you begin to create the transaction. */
    #[Property]
    public ?bool $createVatTransaction;

    /** The top part &gt; Skip VAT amount validation &gt; A check box that (if selected) causes automatic validation of a VAT-related transaction that you create manually to be skipped. */
    #[Property]
    public ?bool $skipVatAmountValidation;

    /** System generated information. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    #[Property]
    public ?string $transactionCode;

    /** The Table part &gt; Transaction description &gt; A description of the transaction or any comments relevant to the transaction. */
    #[Property]
    public ?string $transactionCodeDescription;

    /** The top part &gt; Branch &gt;  The branch to which this batch is related. This field is available if your company is set up with branches. */
    #[Property]
    public ?string $branch;

    /**
     * Identifier that represents a specific version of the resource.
     * It helps to prevent simultaneous updates of the resource from overwriting each other (by using ETags and If-Match headers)
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $timeStamp;

    #[Property]
    public ?array $journalTransactionLines;

    #[Property]
    public ?array $attachments;

    #[Property]
    public ?string $errorInfo;
}
