<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * Organization Query Parameters
 */
class OrganizationQueryParameters extends Model
{
    /** True to expand all Branches related to this Organization. */
    #[Property]
    public ?bool $expandBranches;

    /** True to expand payment settings for organization. */
    #[Property]
    public ?bool $expandBankSettings;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /** Greater than value. The item which is the object for this, varies from API to API. */
    #[Property]
    public ?string $greaterThanValue;
}
