<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\CashSaleStatusEnum;
use Pionect\VismaSdk\Enums\PaymentTypeEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * This class represents a Payment in PaymentController. Used by getting data.
 *
 * @method static \Pionect\VismaSdk\Factories\PaymentDtoFactory testFactory()
 */
class PaymentDto extends SpatieData
{
    /** @use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory<\Pionect\VismaSdk\Factories\PaymentDtoFactory> */
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /**
         * The top part > Type > The type of a document. The following types are
         * available: Payment, CreditNote, Prepayment, Customer refund, Void payment,
         * Balance write-off
         */
        public ?PaymentTypeEnum $type = null,
        /**
         * The top part > Ref.no > The unique identifier for the payment. This number is
         * automatically generated by the system for a new payment document, based on
         * the number series	in the AR101000 window.
         */
        public ?string $refNbr = null,
        /**
         * The top part > Status > The status of the customer payment, which for a new
         * document is either Balanced or On hold. [On hold, Balanced, Voided,
         * Scheduled, Open, Closed, Pending print, Pending email, Credit hold, CcHold,
         * Reserved]
         */
        public ?CashSaleStatusEnum $status = null,
        /**
         * The top part > Hold >  A check box that indicates (if selected) that the
         * document is a draft with the On hold status. This check box is unavailable
         * for debit adjustments.
         */
        public ?bool $hold = null,
        /**
         * Mandatory field: The top part > Date* > The date when a payment is applied to
         * a document (invoice or note). The field display the current business date for
         * tunapplied or partially applied payments and the latest application date for
         * the closed payment
         */
        public ?\Carbon\Carbon $applicationDate = null,
        /**
         * Mandatory field: The top part > Financial period* > The period to which the
         * payment should be applied, which the system fills in based on the date.
         */
        public ?string $applicationPeriod = null,
        /**
         * Mandatory field: The top part > Payment ref.* > A secondary payment reference
         * identifier, which can be a system-generated number or an external reference
         * number entered manually.
         */
        public ?string $paymentRef = null,
        public ?CustomerInPaymentDto $customer = null,
        public ?LocationInPaymentDto $location = null,
        public ?PaymentMethodInPaymentDto $paymentMethod = null,
        /**
         * Mandatory field: The top part > Cash account* > The default cash account
         * associated with the payment method; this field is not available for credit
         * notes.
         */
        public ?string $cashAccount = null,
        /** The top part > Currency > The currency of the payment document. */
        public ?string $currency = null,
        /**
         * The top part > Payment amount > The total of the payment that is entered
         * manually.
         */
        public int|float|null $paymentAmount = null,
        /**
         * The top part > Invoice text > A user-defined description of the payment. 50
         * alphanumeric characters.
         */
        public ?string $invoiceText = null,
        /**
         * The top part > Applied to documents > The total of the documents to which
         * payment is to be applied.
         */
        public int|float|null $appliedToDocuments = null,
        /**
         * The top part > Applied to orders > The total of the orders for which payment
         * is reserved, minus the amount transferred to invoice.
         */
        public int|float|null $appliedToOrders = null,
        /** The top part > Available balance > The amount that has not been applied. */
        public int|float|null $availableBalance = null,
        /** The top part > Write-off amount > The amount that has been written off. */
        public int|float|null $writeOffAmount = null,
        /**
         * The top part > Finance charges > The total on all finance charges applied to
         * this document.
         */
        public int|float|null $financeCharges = null,
        /**
         * The top part > Deducted charges > The total amount of bank charges deducted
         * by bank from the payment amount on your cash account (bank account).
         */
        public int|float|null $deductedCharges = null,
        public ?string $branch = null,
        /** Systemgenerated information. */
        public ?\Carbon\Carbon $lastModifiedDateTime = null,
        /**
         * @var PaymentLineDto[]|null
         *                            Documents to apply tab >
         */
        public ?array $paymentLines = null,
        /**
         * @var OrderToApplyDto[]|null
         *                             Orders to apply tab >
         */
        public ?array $ordersToApply = null,
        public ?FinancialDetailsInPaymentDto $financialDetails = null,
        /**
         * Payment amount calculated in your default (base) currency. This field is
         * applicable if the amount is given in another currency than your default.
         */
        public int|float|null $paymentAmountInCurrency = null,
        /**
         * Available Balance calculated in your default (base) currency. This field is
         * applicable if the amount is given in another currency than your default.
         */
        public int|float|null $availableBalanceInCurrency = null,
        /**
         * Identifier that represents a specific version of the resource.
         * It helps to prevent simultaneous updates of the resource from overwriting
         * each other (by using ETags and If-Match headers)
         */
        public ?string $timeStamp = null,
        public ?string $errorInfo = null,
    ) {}
}
