<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * @extends \Pionect\VismaSdk\Foundation\Hydration\Model<\Pionect\VismaSdk\Factories\PaymentQueryParametersFactory>
 *
 * @method static \Pionect\VismaSdk\Factories\PaymentQueryParametersFactory factory()
 */
class PaymentQueryParameters extends Model
{
    /** Payment number */
    #[Property]
    public ?string $paymentNbr;

    #[Property]
    public ?string $paymentType;

    /** Enter Customer */
    #[Property]
    public ?string $customer;

    /** Enter the from-value for Ref. no. */
    #[Property]
    public ?string $greaterThanValue;

    /** Enter Invoice Ref Nbr */
    #[Property]
    public ?string $invoiceRefNbr;

    /** The status of the document. Use the dropdown to select status. */
    #[Property]
    public ?string $status;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $numberToRead;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $skipRecords;

    /** Enter field to order your records by. */
    #[Property]
    public ?string $orderBy;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /** Filter by Branch */
    #[Property]
    public ?string $branch;

    /**
     * This value indicates the document date. Use it to retrieve all records that have the Document Date since that time, up to the future.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     *
     * _Note:_ __DocDate__ and __DocDateCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $docDate;

    /**
     * This value represents the condition to be applied to the Document Date when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __DocDate__ and __DocDateCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $docDateCondition;

    /** Filter by financial period, format YYYYPP */
    #[Property]
    public ?string $financialPeriod;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;

    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     */
    #[Property]
    public ?int $pageSize;
}
