<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * This class represents a Payment in PaymentController. Used by getting data.
 */
class PaymentDto extends Model
{
    /** The top part &gt; Ref.no &gt; The unique identifier for the payment. This number is automatically generated by the system for a new payment document, based on the number series	in the AR101000 window. */
    #[Property]
    public ?string $refNbr;

    /** The top part &gt; Status &gt; The status of the customer payment, which for a new document is either Balanced or On hold. [On hold, Balanced, Voided, Scheduled, Open, Closed, Pending print, Pending email, Credit hold, CcHold, Reserved] */
    #[Property]
    public ?string $status;

    /** The top part &gt; Hold &gt;  A check box that indicates (if selected) that the document is a draft with the On hold status. This check box is unavailable for debit adjustments. */
    #[Property]
    public ?bool $hold;

    /** Mandatory field: The top part &gt; Date* &gt; The date when a payment is applied to a document (invoice or note). The field display the current business date for tunapplied or partially applied payments and the latest application date for the closed payment */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $applicationDate;

    /** Mandatory field: The top part &gt; Financial period* &gt; The period to which the payment should be applied, which the system fills in based on the date. */
    #[Property]
    public ?string $applicationPeriod;

    /** Mandatory field: The top part &gt; Payment ref.* &gt; A secondary payment reference identifier, which can be a system-generated number or an external reference number entered manually. */
    #[Property]
    public ?string $paymentRef;

    #[Property]
    public ?\customerInPaymentDto $customer;

    #[Property]
    public ?\locationInPaymentDto $location;

    #[Property]
    public ?\paymentMethodInPaymentDto $paymentMethod;

    /** Mandatory field: The top part &gt; Cash account* &gt; The default cash account associated with the payment method; this field is not available for credit notes. */
    #[Property]
    public ?string $cashAccount;

    /** The top part &gt; Currency &gt; The currency of the payment document. */
    #[Property]
    public ?string $currency;

    /** The top part &gt; Payment amount &gt; The total of the payment that is entered manually. */
    #[Property]
    public ?float $paymentAmount;

    /** The top part &gt; Invoice text &gt; A user-defined description of the payment. 50 alphanumeric characters. */
    #[Property]
    public ?string $invoiceText;

    /** The top part &gt; Applied to documents &gt; The total of the documents to which payment is to be applied. */
    #[Property]
    public ?float $appliedToDocuments;

    /** The top part &gt; Applied to orders &gt; The total of the orders for which payment is reserved, minus the amount transferred to invoice. */
    #[Property]
    public ?float $appliedToOrders;

    /** The top part &gt; Available balance &gt; The amount that has not been applied. */
    #[Property]
    public ?float $availableBalance;

    /** The top part &gt; Write-off amount &gt; The amount that has been written off. */
    #[Property]
    public ?float $writeOffAmount;

    /** The top part &gt; Finance charges &gt; The total on all finance charges applied to this document. */
    #[Property]
    public ?float $financeCharges;

    /** The top part &gt; Deducted charges &gt; The total amount of bank charges deducted by bank from the payment amount on your cash account (bank account). */
    #[Property]
    public ?float $deductedCharges;

    #[Property]
    public ?string $branch;

    /** Systemgenerated information. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /** Documents to apply tab &gt; */
    #[Property]
    public ?array $paymentLines;

    /** Orders to apply tab &gt; */
    #[Property]
    public ?array $ordersToApply;

    #[Property]
    public ?\financialDetailsInPaymentDto $financialDetails;

    /** Payment amount calculated in your default (base) currency. This field is applicable if the amount is given in another currency than your default. */
    #[Property]
    public ?float $paymentAmountInCurrency;

    /** Available Balance calculated in your default (base) currency. This field is applicable if the amount is given in another currency than your default. */
    #[Property]
    public ?float $availableBalanceInCurrency;

    /**
     * Identifier that represents a specific version of the resource.
     * It helps to prevent simultaneous updates of the resource from overwriting each other (by using ETags and If-Match headers)
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $timeStamp;

    #[Property]
    public ?string $errorInfo;

    #[Property]
    public ?\MetadataDto $metadata;
}
