<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\TemplateNumberDescriptionStatusEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\ProjectBasicQueryParametersFactory testFactory()
 */
class ProjectBasicQueryParameters extends SpatieData
{
    /** @use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory<\Pionect\VismaSdk\Factories\ProjectBasicQueryParametersFactory> */
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /** Select project status. */
        public ?TemplateNumberDescriptionStatusEnum $status = null,
        /** Project name/description */
        public ?string $description = null,
        /** Identifies the Project */
        public ?string $projectId = null,
        /** Project's start date */
        public ?\Carbon\Carbon $startDate = null,
        /** Set to true to return the non-project. */
        public ?bool $nonProject = null,
        /** Identifies the Project by ID and description */
        public ?string $projectIdDesc = null,
        /** Identifies the Project by its publicId */
        public ?string $publicId = null,
        /** Id of the employee where access restrictions apply */
        public ?string $restrictedEmployee = null,
        /** Id of the odp user where access restrictions apply */
        public ?int $restrictedUser = null,
        /** If the project is visible in the Supplier ledger */
        public ?bool $visibleInAp = null,
        /** If the project is visible in the Customer ledger */
        public ?bool $visibleInAr = null,
        /** If the project is visible in the Cash management workspace */
        public ?bool $visibleInCa = null,
        /** If the project is visible in the CRM workspace */
        public ?bool $visibleInCr = null,
        /** If the project is visible in the Expense workspace */
        public ?bool $visibleInEa = null,
        /** If the project is visible in the General ledger workspace */
        public ?bool $visibleInGl = null,
        /** If the project is visible in the Inventory workspace */
        public ?bool $visibleInIn = null,
        /** If the project is visible in the Purchases workspace */
        public ?bool $visibleInPo = null,
        /** If the project is visible in the Sales workspace */
        public ?bool $visibleInSo = null,
        /** If the project is visible in the Time entities workspace */
        public ?bool $visibleInTa = null,
        /**
         * This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.
         */
        public ?int $numberToRead = null,
        /**
         * This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.
         */
        public ?int $skipRecords = null,
        /**
         * Greater than value. The item which is the object for this, varies from API to
         * API.
         */
        public ?string $greaterThanValue = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        /** Creation date and time. */
        public ?string $createdDateTime = null,
        /** System-retrieved information for state/condition */
        public ?string $createdDateTimeCondition = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
