<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\InventoryAdjustmentStatusEnum;
use Pionect\VismaSdk\Enums\JournalTransactionLineModuleEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\ProjectTransactionQueryParametersFactory testFactory()
 */
class ProjectTransactionQueryParameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /** Select to filter on module; e.g. AR, AP, IN etc. */
        public ?JournalTransactionLineModuleEnum $module = null,
        /** The status of the document. */
        public ?InventoryAdjustmentStatusEnum $status = null,
        /** Filter on project ID. */
        public ?string $project = null,
        /** Filter on Task ID. */
        public ?string $projectTask = null,
        /** Filter invoiceable project tasks. */
        public ?bool $billable = null,
        /** Filter on branch for the project transation. */
        public ?string $branch = null,
        /** Filter on the registration date for the project transaction. */
        public ?\Carbon\Carbon $date = null,
        /** Mandatory. Start date for the task. */
        public ?string $fromPeriod = null,
        /** Mandatory. End date for the task. */
        public ?string $toPeriod = null,
        /**
         * This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.
         */
        public ?int $numberToRead = null,
        /**
         * This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.
         */
        public ?int $skipRecords = null,
        /** Expands project transaction notes */
        public ?bool $expandNote = null,
        /**
         * Greater than value. The item which is the object for this, varies from API to
         * API.
         */
        public ?string $greaterThanValue = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        /** Creation date and time. */
        public ?string $createdDateTime = null,
        /** System-retrieved information for state/condition */
        public ?string $createdDateTimeCondition = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
