<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

class ProjectBasicQueryParameters extends Model
{
    /** Select project status. */
    #[Property]
    public ?string $status;

    /** Project name/description */
    #[Property]
    public ?string $description;

    /** Identifies the Project */
    #[Property]
    public ?string $projectId;

    /** Project's start date */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $startDate;

    /** Set to true to return the non-project. */
    #[Property]
    public ?bool $nonProject;

    /** Identifies the Project by ID and description */
    #[Property]
    public ?string $projectIdDesc;

    /** Identifies the Project by its publicId */
    #[Property]
    public ?string $publicId;

    /** Id of the employee where access restrictions apply */
    #[Property]
    public ?string $restrictedEmployee;

    /** Id of the odp user where access restrictions apply */
    #[Property]
    public ?int $restrictedUser;

    /** If the project is visible in the Supplier ledger */
    #[Property]
    public ?bool $visibleInAp;

    /** If the project is visible in the Customer ledger */
    #[Property]
    public ?bool $visibleInAr;

    /** If the project is visible in the Cash management workspace */
    #[Property]
    public ?bool $visibleInCa;

    /** If the project is visible in the CRM workspace */
    #[Property]
    public ?bool $visibleInCr;

    /** If the project is visible in the Expense workspace */
    #[Property]
    public ?bool $visibleInEa;

    /** If the project is visible in the General ledger workspace */
    #[Property]
    public ?bool $visibleInGl;

    /** If the project is visible in the Inventory workspace */
    #[Property]
    public ?bool $visibleInIn;

    /** If the project is visible in the Purchases workspace */
    #[Property]
    public ?bool $visibleInPo;

    /** If the project is visible in the Sales workspace */
    #[Property]
    public ?bool $visibleInSo;

    /** If the project is visible in the Time entities workspace */
    #[Property]
    public ?bool $visibleInTa;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $numberToRead;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $skipRecords;

    /** Greater than value. The item which is the object for this, varies from API to API. */
    #[Property]
    public ?string $greaterThanValue;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /** Creation date and time. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $createdDateTime;

    /** System-retrieved information for state/condition */
    #[Property]
    public ?string $createdDateTimeCondition;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;

    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     */
    #[Property]
    public ?int $pageSize;
}
