<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * @extends \Pionect\VismaSdk\Foundation\Hydration\Model<\Pionect\VismaSdk\Factories\ProjectTransactionQueryParametersFactory>
 *
 * @method static \Pionect\VismaSdk\Factories\ProjectTransactionQueryParametersFactory factory()
 */
class ProjectTransactionQueryParameters extends Model
{
    /** Select to filter on module; e.g. AR, AP, IN etc. */
    #[Property]
    public ?string $module;

    /** The status of the document. */
    #[Property]
    public ?string $status;

    /** Filter on project ID. */
    #[Property]
    public ?string $project;

    /** Filter on Task ID. */
    #[Property]
    public ?string $projectTask;

    /** Filter invoiceable project tasks. */
    #[Property]
    public ?bool $billable;

    /** Filter on branch for the project transation. */
    #[Property]
    public ?string $branch;

    /** Filter on the registration date for the project transaction. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $date;

    /** Mandatory. Start date for the task. */
    #[Property]
    public ?string $fromPeriod;

    /** Mandatory. End date for the task. */
    #[Property]
    public ?string $toPeriod;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $numberToRead;

    /** This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords. */
    #[Property]
    public ?int $skipRecords;

    /** Expands project transaction notes */
    #[Property]
    public ?bool $expandNote;

    /** Greater than value. The item which is the object for this, varies from API to API. */
    #[Property]
    public ?string $greaterThanValue;

    /**
     * This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    /**
     * This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     */
    #[Property]
    public ?string $lastModifiedDateTimeCondition;

    /** Creation date and time. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $createdDateTime;

    /** System-retrieved information for state/condition */
    #[Property]
    public ?string $createdDateTimeCondition;

    /** Pagination parameter. Page number. */
    #[Property]
    public ?int $pageNumber;

    /**
     * Pagination parameter. Number of items to be collected.
     * Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     * If requested page size is greater than allowed max page size, request will be limited to max page size.
     */
    #[Property]
    public ?int $pageSize;
}
