<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\TaskStatusEnum;
use Pionect\VismaSdk\Enums\TemplateNumberDescriptionStatusEnum;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\ProjectQueryParametersFactory testFactory()
 */
class ProjectQueryParameters extends SpatieData
{
    /** @use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory<\Pionect\VismaSdk\Factories\ProjectQueryParametersFactory> */
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /** Use drop down and select Status. */
        public ?TemplateNumberDescriptionStatusEnum $status = null,
        /** If the project is a template */
        public ?bool $systemTemplate = null,
        /** If the project is visible in AP */
        #[MapName('visibleInAP')]
        public ?bool $visibleInAp = null,
        /** Project’s start date */
        public ?\Carbon\Carbon $startDate = null,
        /** Expands project atributes */
        public ?bool $expandAttribute = null,
        /** Identifies the attributes */
        public ?string $attributes = null,
        /** Use drop down and select Status. */
        public ?TaskStatusEnum $taskStatus = null,
        /** If the project task is visible in the Supplier ledger */
        public ?bool $taskVisibleInAp = null,
        /** If the project task is visible in the Customer ledger */
        public ?bool $taskVisibleInAr = null,
        /** If the project task is visible in the Cash management workspace */
        public ?bool $taskVisibleInCa = null,
        /** If the project task is visible in the CRM workspace */
        public ?bool $taskVisibleInCr = null,
        /** If the project task is visible in the Expense workspace */
        public ?bool $taskVisibleInEa = null,
        /** If the project task is visible in the General ledger workspace */
        public ?bool $taskVisibleInGl = null,
        /** If the project task is visible in the Inventory workspace */
        public ?bool $taskVisibleInIn = null,
        /** If the project task is visible in the Purchases workspace */
        public ?bool $taskVisibleInPo = null,
        /** If the project task is visible in the Sales workspace */
        public ?bool $taskVisibleInSo = null,
        /** If the project task is visible in the Time entities workspace */
        public ?bool $taskVisibleInTa = null,
        /** Set to true to return the non-project. */
        public ?bool $nonProject = null,
        /** Identifies the Project by its publicId */
        public ?string $publicId = null,
        /** ID of the employee where access restrictions apply */
        public ?string $restrictedEmployee = null,
        /** Id of the odp user where access restrictions apply */
        public ?int $restrictedUser = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        /** Creation date and time. */
        public ?string $createdDateTime = null,
        /** System-retrieved information for state/condition */
        public ?string $createdDateTimeCondition = null,
        /** The branch name. */
        public ?string $branch = null,
        /** If the project is on hold */
        public ?bool $onHold = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
