<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\PurchaseReceiptsStatusEnum;
use Pionect\VismaSdk\Enums\PurchaseReceiptsTypeEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\PurchaseReceiptV2queryParametersFactory testFactory()
 */
class PurchaseReceiptV2queryParameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        public ?PurchaseReceiptsTypeEnum $receiptType = null,
        public ?PurchaseReceiptsStatusEnum $status = null,
        public ?string $greaterThanValue = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        public ?string $supplier = null,
        public ?string $poOrderNbr = null,
        public ?bool $expandNote = null,
        public ?string $branch = null,
        /** Filter by financial period, format YYYYPP */
        public ?string $finPeriod = null,
        /**
         * This value indicates the receipt date. Use it to retrieve all records that
         * have the receipt date since that time, up to the future.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __ReceiptDate__ and __ReceiptDateCondition__ are __mutually
         * inclusive__.
         */
        public ?string $receiptDate = null,
        /**
         * This value represents the condition to be applied to the order date when
         * retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __ReceiptDate__ and __ReceiptDateCondition__ are __mutually
         * inclusive__.
         */
        public ?string $receiptDateCondition = null,
        /**
         * This value indicates the date the document is due. Use it to retrieve all
         * records that have the due date since that time, up to the future.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __DueDate__ and __DueDateCondition__ are __mutually inclusive__.
         */
        public ?string $dueDate = null,
        /**
         * This value represents the condition to be applied to the Due Date when
         * retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __DueDate__ and __DueDateCondition__ are __mutually inclusive__.
         */
        public ?string $dueDateCondition = null,
        /**
         * Parameter to include custom free fields information in the result set, if
         * true then custom free fields will be included in the result set
         */
        public ?bool $includeCustomFreeFields = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
