<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * This class represents a SOOrder in SOOrderController. Used by getting data.
 */
class SalesOrderDto extends Model
{
    /** Mandatory field: The top part &gt; Project* &gt; The field consists of Project ID and Project description. Project ID: The identifier for the project with which this document is associated, or the code indicating that this document is not associated with any project; the non-project code is specified in the Project accounting preferences (PM101000) window. */
    #[Property]
    public ?string $projectCd;

    /** The top part &gt; Print description on invoice &gt; A check box */
    #[Property]
    public ?bool $printDescriptionOnInvoice;

    /** The top part &gt; Print note on external sales documents &gt; A check box */
    #[Property]
    public ?bool $printNoteOnExternalDocuments;

    /** The top part &gt; Print line note on internal sales documents &gt; A check box */
    #[Property]
    public ?bool $printNoteOnInternalDocuments;

    #[Property]
    public ?soBillingContactInSalesOrderDto $soBillingContact;

    #[Property]
    public ?soBillingAddressInSalesOrderDto $soBillingAddress;

    #[Property]
    public ?customerVATZoneInSalesOrderDto $customerVatzone;

    /** Financial settings tab &gt; Financial information section &gt; Invoice separately &gt; A check box that indicating that this document is to be invoiced separately (if that is required). */
    #[Property]
    public ?bool $invoiceSeparately;

    /** Financial settings tab &gt; Financial information section &gt; Invoice no.&gt; The invoice number of the invoice generated for this order. */
    #[Property]
    public ?string $invoiceNbr;

    /** Financial settings tab &gt; Financial information section &gt; Invoice date&gt; The date of the invoice generated for the order. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $invoiceDate;

    #[Property]
    public ?termsInSalesOrderDto $terms;

    /** Financial settings tab &gt; Financial information section &gt; Due date &gt; The due date of the invoice according to the credit terms. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $dueDate;

    /** Financial settings tab &gt; Financial information section &gt; Cash discount date &gt; The date when the cash discount is available for the invoice based on the credit terms. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $cashDiscountDate;

    /** The Financial settings tab &gt; Financial information section &gt; Post period &gt; The period to post the transactions generated by the invoice. Format MMYYYY. */
    #[Property]
    public ?string $postPeriod;

    #[Property]
    public ?salesPersonInSalesOrderDto $salesPerson;

    /** The Commissions tab &gt; Commission (%) &gt; The percentage of commission generally earned by the salesperson. */
    #[Property]
    public ?string $commissionPercent;

    /** The Commissions tab &gt; Commission amt. &gt;	The commission amount earned by the salesperson on this document. */
    #[Property]
    public ?string $commissionAmount;

    /** The Commissions tab &gt; Commissionable amount	&gt; The amount used to calculate the commission. */
    #[Property]
    public ?string $commissionableAmount;

    #[Property]
    public ?ownerInSalesOrderDto $owner;

    /** Mandatory field: The top part &gt; Order type* &gt; The type of the document, which is one of the predefined order types or a custom order type created by using the window SO201000. */
    #[Property]
    public ?string $origOrderType;

    /** The top part &gt; Order no. &gt; The order number of the document. */
    #[Property]
    public ?string $origOrderNbr;

    #[Property]
    public ?soShippingContactInSalesOrderDto $soShippingContact;

    #[Property]
    public ?soShippingAddressInSalesOrderDto $soShippingAddress;

    /** Delivery settings tab &gt; Shipping information section &gt; Sched. shipment &gt; The date when the ordered goods are scheduled to be shipped. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $schedShipment;

    /** Delivery settings tab &gt; Shipping information section &gt; Ship separately &gt; This check box indicates that the goods for the customer should be shipped separately for each sales order. */
    #[Property]
    public ?bool $shipSeparately;

    /** Delivery settings tab &gt; Shipping information section &gt; Shipping rule &gt; An option that controls whether incomplete and partial shipments for the order are allowed. */
    #[Property]
    public ?string $shipComplete;

    /** Delivery settings tab &gt; Shipping information section &gt; Cancel by &gt; The date when the order should be cancelled if the Back order allowed option has been selected in the Shipping rule field. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $cancelBy;

    /** The Delivery settings tab &gt; The Shipping information section &gt; Cancelled &gt; A check box that indicates that the order has been cancelled on the date specified in Cancel by. */
    #[Property]
    public ?bool $canceled;

    #[Property]
    public ?preferredWarehouseInSalesOrderDto $preferredWarehouse;

    #[Property]
    public ?shipViaInSalesOrderDto $shipVia;

    #[Property]
    public ?fobPointInSalesOrderDto $fobPoint;

    /** Delivery settings tab &gt; Shipping information section &gt; Priority &gt; Field only for informational purposes. The level of priority for processing order of this customer, as specified for the customer on the Shipping settings tab on the AR303000 window. */
    #[Property]
    public ?int $priority;

    #[Property]
    public ?shippingTermsInSalesOrderDto $shippingTerms;

    #[Property]
    public ?shippingZoneInSalesOrderDto $shippingZone;

    /** Delivery settings tab &gt; Shipping information section &gt; Residential delivery &gt; A check box that you select to indicate that the shipment should be delivered to a residential area. */
    #[Property]
    public ?bool $residentialDelivery;

    /** Delivery settings tab &gt; Shipping information section &gt; Saturday delivery &gt; A check box that indicates that the order may be delivered on Saturday. */
    #[Property]
    public ?bool $saturdayDelivery;

    /** Delivery settings tab &gt; Shipping information section &gt; Insurance &gt; A check box that you select to indicate that insurance is required for this order. */
    #[Property]
    public ?bool $insurance;

    #[Property]
    public ?transactionTypeInSalesOrderDto $transactionType;

    #[Property]
    public ?paymentMethodInSalesOrderDto $paymentMethod;

    /** Payment settings tab &gt; Cash account */
    #[Property]
    public ?string $cashAccount;

    /** Payment settings tab &gt; Payment ref. */
    #[Property]
    public ?string $paymentRef;

    /** A check box indicating if the document is Rot/rut deductible (applicable for the Swedish markets) */
    #[Property]
    public ?bool $isRotRutDeductible;

    /** A check box indicating if the document is emailed */
    #[Property]
    public ?bool $emailed;

    /** Document details tab &gt; */
    #[Property]
    public ?array $lines;

    /** Shipment tab &gt; */
    #[Property]
    public ?array $shipments;

    /** Mandatory field: The top part &gt; Order type &gt; The type of the document, which is one of the predefined order types or a custom order type created by using the (SO201000) window. */
    #[Property]
    public ?string $orderType;

    /** The top part &gt; Order no.: &gt; The reference number of the document. */
    #[Property]
    public ?string $orderNo;

    /** The top part &gt; Status &gt; The status of the document, which can be one of the following options: On hold, Credit hold, Pending aååroval, Rejected, Open, Cancelled, Shipping, Back order, Invoiced, Completed. */
    #[Property]
    public ?string $status;

    /** The top part &gt; Hold &gt; A check box that you select if the document is on hold and should not be processed further at this time. */
    #[Property]
    public ?bool $hold;

    /** Mandatory field: The top part &gt; Date* &gt;  The date of the document. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $date;

    /** Mandatory field: The top part &gt; Requested on &gt; The date when the customer wants to receive the goods; this date provides the default values for the Requested on dates for order lines. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $requestOn;

    /** The top part &gt; Customer order &gt; The reference number of the original customer document that the sales order is based on. */
    #[Property]
    public ?string $customerOrder;

    /** The top part &gt; External reference &gt; The reference number of the sales order in a third-party application if Visma.net Financials is integrated with such an application and imports the sales orders from it. */
    #[Property]
    public ?string $customerRefNo;

    #[Property]
    public ?customerInSalesOrderDto $customer;

    /** The top part &gt; Contact &gt; The contact person of the customer. */
    #[Property]
    public ?int $contactId;

    #[Property]
    public ?locationInSalesOrderDto $location;

    /** The top part &gt; Currency &gt; The currency of the document. */
    #[Property]
    public ?string $currency;

    /** The top part &gt; Description &gt; A brief description of the document. */
    #[Property]
    public ?string $description;

    /**
     * The top part &gt; Order total &gt; The total amount of the document, which is calculated as follows:
     * Line Total + Misc.Charges + Freight + Premium Freight – Discount Total+ Tax Total
     */
    #[Property]
    public ?float $orderTotal;

    #[Property]
    public ?float $orderTotalInBaseCurrency;

    /** The top part &gt; VAT taxable total &gt; The document total that is subject to VAT. */
    #[Property]
    public ?float $vatTaxableTotal;

    #[Property]
    public ?float $vatTaxableTotalInBaseCurrency;

    /** The top part &gt; VAT exempt total &gt; The document total that is exempt from VAT. */
    #[Property]
    public ?float $vatExemptTotal;

    #[Property]
    public ?float $vatExemptTotalInBaseCurrency;

    /** The top part &gt; VAT total &gt; The total amount of tax paid on the document. */
    #[Property]
    public ?float $taxTotal;

    #[Property]
    public ?float $taxTotalInBaseCurrency;

    #[Property]
    public ?float $exchangeRate;

    #[Property]
    public ?float $discountTotal;

    #[Property]
    public ?float $discountTotalInBaseCurrency;

    /** Background information collected from the system. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    #[Property]
    public ?branchNumberInSalesOrderDto $branchNumber;

    /** Icon Notes on top of the window &gt; Pop-up window for providing any user-defined text connected to the order. */
    #[Property]
    public ?string $note;

    /** The data containing information about the document attachments */
    #[Property]
    public ?array $attachments;

    #[Property]
    public ?string $errorInfo;
}
