<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\SalesOrderLineShipCompleteEnum;
use Pionect\VismaSdk\Enums\SalesOrderQueryParametersStatusEnum;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data as SpatieData;

/**
 * This class represents a SOOrder in SOOrderController. Used by getting data.
 *
 * @method static \Pionect\VismaSdk\Factories\SalesOrderDtoFactory testFactory()
 */
class SalesOrderDto extends SpatieData
{
    /** @use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory<\Pionect\VismaSdk\Factories\SalesOrderDtoFactory> */
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        /**
         * Mandatory field: The top part > Project* > The field consists of Project ID
         * and Project description. Project ID: The identifier for the project with
         * which this document is associated, or the code indicating that this document
         * is not associated with any project; the non-project code is specified in the
         * Project accounting preferences (PM101000) window.
         */
        #[MapName('projectCD')]
        public ?string $projectCd = null,
        /** The top part > Print description on invoice > A check box */
        public ?bool $printDescriptionOnInvoice = null,
        /** The top part > Print note on external sales documents > A check box */
        public ?bool $printNoteOnExternalDocuments = null,
        /** The top part > Print line note on internal sales documents > A check box */
        public ?bool $printNoteOnInternalDocuments = null,
        public ?SoBillingContactInSalesOrderDto $soBillingContact = null,
        public ?SoBillingAddressInSalesOrderDto $soBillingAddress = null,
        #[MapName('customerVATZone')]
        public ?CustomerVatzoneInSalesOrderDto $customerVatzone = null,
        /**
         * Financial settings tab > Financial information section > Invoice separately >
         * A check box that indicating that this document is to be invoiced separately
         * (if that is required).
         */
        public ?bool $invoiceSeparately = null,
        /**
         * Financial settings tab > Financial information section > Invoice no.> The
         * invoice number of the invoice generated for this order.
         */
        public ?string $invoiceNbr = null,
        /**
         * Financial settings tab > Financial information section > Invoice date> The
         * date of the invoice generated for the order.
         */
        public ?\Carbon\Carbon $invoiceDate = null,
        public ?TermsInSalesOrderDto $terms = null,
        /**
         * Financial settings tab > Financial information section > Due date > The due
         * date of the invoice according to the credit terms.
         */
        public ?\Carbon\Carbon $dueDate = null,
        /**
         * Financial settings tab > Financial information section > Cash discount date >
         * The date when the cash discount is available for the invoice based on the
         * credit terms.
         */
        public ?\Carbon\Carbon $cashDiscountDate = null,
        /**
         * The Financial settings tab > Financial information section > Post period >
         * The period to post the transactions generated by the invoice. Format MMYYYY.
         */
        public ?string $postPeriod = null,
        public ?SalesPersonInSalesOrderDto $salesPerson = null,
        /**
         * The Commissions tab > Commission (%) > The percentage of commission generally
         * earned by the salesperson.
         */
        public ?string $commissionPercent = null,
        /**
         * The Commissions tab > Commission amt. >	The commission amount earned by the
         * salesperson on this document.
         */
        public ?string $commissionAmount = null,
        /**
         * The Commissions tab > Commissionable amount	> The amount used to calculate
         * the commission.
         */
        public ?string $commissionableAmount = null,
        public ?OwnerInSalesOrderDto $owner = null,
        /**
         * Mandatory field: The top part > Order type* > The type of the document, which
         * is one of the predefined order types or a custom order type created by using
         * the window SO201000.
         */
        public ?string $origOrderType = null,
        /** The top part > Order no. > The order number of the document. */
        public ?string $origOrderNbr = null,
        public ?SoShippingContactInSalesOrderDto $soShippingContact = null,
        public ?SoShippingAddressInSalesOrderDto $soShippingAddress = null,
        /**
         * Delivery settings tab > Shipping information section > Sched. shipment > The
         * date when the ordered goods are scheduled to be shipped.
         */
        public ?\Carbon\Carbon $schedShipment = null,
        /**
         * Delivery settings tab > Shipping information section > Ship separately > This
         * check box indicates that the goods for the customer should be shipped
         * separately for each sales order.
         */
        public ?bool $shipSeparately = null,
        /**
         * Delivery settings tab > Shipping information section > Shipping rule > An
         * option that controls whether incomplete and partial shipments for the order
         * are allowed.
         */
        public ?SalesOrderLineShipCompleteEnum $shipComplete = null,
        /**
         * Delivery settings tab > Shipping information section > Cancel by > The date
         * when the order should be cancelled if the Back order allowed option has been
         * selected in the Shipping rule field.
         */
        public ?\Carbon\Carbon $cancelBy = null,
        /**
         * The Delivery settings tab > The Shipping information section > Cancelled > A
         * check box that indicates that the order has been cancelled on the date
         * specified in Cancel by.
         */
        public ?bool $canceled = null,
        public ?PreferredWarehouseInSalesOrderDto $preferredWarehouse = null,
        public ?ShipViaInSalesOrderDto $shipVia = null,
        public ?FobPointInSalesOrderDto $fobPoint = null,
        /**
         * Delivery settings tab > Shipping information section > Priority > Field only
         * for informational purposes. The level of priority for processing order of
         * this customer, as specified for the customer on the Shipping settings tab on
         * the AR303000 window.
         */
        public ?int $priority = null,
        public ?ShippingTermsInSalesOrderDto $shippingTerms = null,
        public ?ShippingZoneInSalesOrderDto $shippingZone = null,
        /**
         * Delivery settings tab > Shipping information section > Residential delivery >
         * A check box that you select to indicate that the shipment should be delivered
         * to a residential area.
         */
        public ?bool $residentialDelivery = null,
        /**
         * Delivery settings tab > Shipping information section > Saturday delivery > A
         * check box that indicates that the order may be delivered on Saturday.
         */
        public ?bool $saturdayDelivery = null,
        /**
         * Delivery settings tab > Shipping information section > Insurance > A check
         * box that you select to indicate that insurance is required for this order.
         */
        public ?bool $insurance = null,
        public ?TransactionTypeInSalesOrderDto $transactionType = null,
        public ?PaymentMethodInSalesOrderDto $paymentMethod = null,
        /** Payment settings tab > Cash account */
        public ?string $cashAccount = null,
        /** Payment settings tab > Payment ref. */
        public ?string $paymentRef = null,
        /**
         * A check box indicating if the document is Rot/rut deductible (applicable for
         * the Swedish markets)
         */
        public ?bool $isRotRutDeductible = null,
        /** A check box indicating if the document is emailed */
        public ?bool $emailed = null,
        /**
         * @var SalesOrderLineDto[]|null
         *                               Document details tab >
         */
        public ?array $lines = null,
        /**
         * @var SalesOrderShipmentDto[]|null
         *                                   Shipment tab >
         */
        public ?array $shipments = null,
        /**
         * Mandatory field: The top part > Order type > The type of the document, which
         * is one of the predefined order types or a custom order type created by using
         * the (SO201000) window.
         */
        public ?string $orderType = null,
        /** The top part > Order no.: > The reference number of the document. */
        public ?string $orderNo = null,
        /**
         * The top part > Status > The status of the document, which can be one of the
         * following options: On hold, Credit hold, Pending aååroval, Rejected, Open,
         * Cancelled, Shipping, Back order, Invoiced, Completed.
         */
        public ?SalesOrderQueryParametersStatusEnum $status = null,
        /**
         * The top part > Hold > A check box that you select if the document is on hold
         * and should not be processed further at this time.
         */
        public ?bool $hold = null,
        /** Mandatory field: The top part > Date* >  The date of the document. */
        public ?\Carbon\Carbon $date = null,
        /**
         * Mandatory field: The top part > Requested on > The date when the customer
         * wants to receive the goods; this date provides the default values for the
         * Requested on dates for order lines.
         */
        public ?\Carbon\Carbon $requestOn = null,
        /**
         * The top part > Customer order > The reference number of the original customer
         * document that the sales order is based on.
         */
        public ?string $customerOrder = null,
        /**
         * The top part > External reference > The reference number of the sales order
         * in a third-party application if Visma.net Financials is integrated with such
         * an application and imports the sales orders from it.
         */
        public ?string $customerRefNo = null,
        public ?CustomerInSalesOrderDto $customer = null,
        /** The top part > Contact > The contact person of the customer. */
        public ?int $contactId = null,
        public ?LocationInSalesOrderDto $location = null,
        /** The top part > Currency > The currency of the document. */
        public ?string $currency = null,
        /** The top part > Description > A brief description of the document. */
        public ?string $description = null,
        /**
         * The top part > Order total > The total amount of the document, which is
         * calculated as follows:
         * Line Total + Misc.Charges + Freight + Premium Freight – Discount Total+ Tax
         * Total
         */
        public int|float|null $orderTotal = null,
        public int|float|null $orderTotalInBaseCurrency = null,
        /** The top part > VAT taxable total > The document total that is subject to VAT. */
        public int|float|null $vatTaxableTotal = null,
        public int|float|null $vatTaxableTotalInBaseCurrency = null,
        /** The top part > VAT exempt total > The document total that is exempt from VAT. */
        public int|float|null $vatExemptTotal = null,
        public int|float|null $vatExemptTotalInBaseCurrency = null,
        /** The top part > VAT total > The total amount of tax paid on the document. */
        public int|float|null $taxTotal = null,
        public int|float|null $taxTotalInBaseCurrency = null,
        public int|float|null $exchangeRate = null,
        public int|float|null $discountTotal = null,
        public int|float|null $discountTotalInBaseCurrency = null,
        /** Background information collected from the system. */
        public ?\Carbon\Carbon $lastModifiedDateTime = null,
        public ?BranchNumberInSalesOrderDto $branchNumber = null,
        /**
         * Icon Notes on top of the window > Pop-up window for providing any
         * user-defined text connected to the order.
         */
        public ?string $note = null,
        /**
         * @var AttachmentDto[]|null
         *                           The data containing information about the document attachments
         */
        public ?array $attachments = null,
        public ?string $errorInfo = null,
    ) {}
}
