<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Foundation\Hydration\Attributes\DateTime;
use Pionect\VismaSdk\Foundation\Hydration\Attributes\Property;
use Pionect\VismaSdk\Foundation\Hydration\Model;

/**
 * This class represents a Shipment in ShipmentController. Used by getting data.
 *
 * @extends \Pionect\VismaSdk\Foundation\Hydration\Model<\Pionect\VismaSdk\Factories\ShipmentDtoFactory>
 *
 * @method static \Pionect\VismaSdk\Factories\ShipmentDtoFactory factory()
 */
class ShipmentDto extends Model
{
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $timeStamp;

    /** The top part &gt; Shipment no &gt; The unique reference number of the document, which is automatically generated by the system. */
    #[Property]
    public ?string $shipmentNumber;

    /** The top part &gt; Type &gt; The type of the shipment document, which can be one of the following options: Shipment, Transfer. */
    #[Property]
    public ?string $shipmentType;

    /** The top part &gt; Status &gt; The status of the document. */
    #[Property]
    public ?string $status;

    /** The top part &gt; Hold &gt; This check box indicates (if selected) that the documents cannot be processed further until the check box is cleared. */
    #[Property]
    public ?bool $hold;

    /** The top part &gt; Operation &gt; The operation to be performed in the Inventory workspace for this shipment: Issue or Receipt. */
    #[Property]
    public ?string $operation;

    /** Mandatory field: The top part &gt; Shipment date* &gt; The date when the document has been created. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $shipmentDate;

    #[Property]
    public ?customerInShipmentDto $customer;

    #[Property]
    public ?locationInShipmentDto $location;

    #[Property]
    public ?fromWarehouseInShipmentDto $fromWarehouse;

    #[Property]
    public ?toWarehouseInShipmentDto $toWarehouse;

    /** Delivery settings tab &gt; Freight currency &gt; By default, it is the currency of the sales order, but you can change it if needed. */
    #[Property]
    public ?string $currencyId;

    #[Property]
    public ?ownerInShipmentDto $owner;

    /** The top part &gt; Shipped quantity &gt; The quantity of goods shipped. */
    #[Property]
    public ?float $shippedQuantity;

    /** The top part &gt; Shipped weight &gt; The weight of the goods shipped. */
    #[Property]
    public ?float $shippedWeight;

    /** The top part &gt; Shipped volume &gt; The total volume of the items in the shipment. */
    #[Property]
    public ?float $shippedVolume;

    /** The top part &gt; Packages &gt; The number of boxes included in this shipment. */
    #[Property]
    public ?int $packages;

    /** The top part &gt; Package weight &gt; The total weight of the shipment that includes the weight of boxes (for boxes determined automatically). */
    #[Property]
    public ?float $packagesWeight;

    /** The top part &gt; Package volume &gt; The total volume of the shipment that includes the volume of boxes (for boxes determined automatically). */
    #[Property]
    public ?float $packagesVolume;

    /** The top part &gt; Control quantity &gt; The control value, which you manually enter as a value equal to the shipped quantity if the Validate shipment total on confirmation check box has been selected in the Sales orders preferences (SO101000) window. */
    #[Property]
    public ?float $controlQuantity;

    #[Property]
    public ?deliveryAddressInShipmentDto $deliveryAddress;

    #[Property]
    public ?deliveryContactInShipmentDto $deliveryContact;

    #[Property]
    public ?shipViaInShipmentDto $shipVia;

    #[Property]
    public ?fobPointInShipmentDto $fobPoint;

    #[Property]
    public ?shippingTermsInShipmentDto $shippingTerms;

    #[Property]
    public ?shippingZoneInShipmentDto $shippingZone;

    /** Delivery settings tab &gt; Shipping information section &gt; Residential delivery &gt; This check box indicates (if selected) that the shipping address is a residential one. */
    #[Property]
    public ?bool $residentialDelivery;

    /** Delivery settings tab &gt; Shipping information section &gt; Saturday delivery &gt; This check box indicates delivery on saturday. */
    #[Property]
    public ?bool $saturdayDelivery;

    #[Property]
    public ?bool $useCustomerAccount;

    /** Delivery settings tab &gt; Shipping information section &gt; Insurance &gt; This check box indicates (if selected) that insurance is required for the shipment. */
    #[Property]
    public ?bool $insurance;

    /** Delivery settings tab &gt; Shipping information section &gt; Freight cost &gt; The freight cost of the shipment. */
    #[Property]
    public ?float $freightCost;

    /** Delivery settings tab &gt; Shipping information section &gt; Freight amt. &gt; The amount of freight the customer will be charged for the shipment. */
    #[Property]
    public ?float $freightAmt;

    #[Property]
    public ?transactionTypeInShipmentDto $transactionType;

    #[Property]
    public ?modeOfTrasportInShipmentDto $modeOfTrasport;

    /** Delivery settings tab &gt; Intrastat section &gt; Container &gt; This check box indicates (if selected) that the shipment gets marked as shipped in container for Intrastat reporting purposes. */
    #[Property]
    public ?bool $container;

    /** Document details tab &gt; */
    #[Property]
    public ?array $shipmentDetailLines;

    /** Orders tab &gt; */
    #[Property]
    public ?array $shipmentOrderLines;

    /** Packages tab &gt; */
    #[Property]
    public ?array $shipmentPackageLines;

    /** System generated information. */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $lastModifiedDateTime;

    #[Property]
    public ?string $note;

    /** A free custom colum of type string with max length 100. */
    #[Property]
    public ?string $customStr1;

    /** A free custom colum of type string with max length 100. */
    #[Property]
    public ?string $customStr2;

    /** A free custom colum of type string with max length 100. */
    #[Property]
    public ?string $customStr3;

    /** A free custom colum of type string with max length 100. */
    #[Property]
    public ?string $customStr4;

    /** A free custom colum of type string with max length 100. */
    #[Property]
    public ?string $customStr5;

    /** A free custom colum of type decimal with max 4 decimals. */
    #[Property]
    public ?float $customDec1;

    /** A free custom colum of type decimal with max 4 decimals. */
    #[Property]
    public ?float $customDec2;

    /** A free custom colum of type int */
    #[Property]
    public ?int $customInt1;

    /** A free custom colum of type int */
    #[Property]
    public ?int $customInt2;

    /** A free custom colum of type DateTime - in UTC timezone */
    #[Property]
    #[DateTime]
    public ?\Carbon\Carbon $customDateTimeUtc1;

    #[Property]
    public ?string $errorInfo;
}
