<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\ShipmentShipmentTypeEnum;
use Pionect\VismaSdk\Enums\ShipmentStatusEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\ShipmentsQueryParametersFactory testFactory()
 */
class ShipmentsQueryParameters extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        public ?int $customerId = null,
        public ?string $customerNumber = null,
        /**
         * This field has been deprecated and will be removed in future versions. The
         * GreaterThanValue parameter has no effect on the result.
         */
        public ?string $greaterThanValue = null,
        /**
         * This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.
         */
        public ?int $numberToRead = null,
        /**
         * This field has been deprecated and will be removed in future versions. Use
         * pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does
         * not work with NumberToRead and SkipRecords.
         */
        public ?int $skipRecords = null,
        /**
         * This field has been deprecated and will be removed in future versions. The
         * OrderBy parameter has no effect on the result.
         */
        public ?string $orderBy = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        public ?ShipmentStatusEnum $status = null,
        public ?int $pageSize = null,
        public ?int $pageNumber = null,
        /** Filter by Shipment Type */
        public ?ShipmentShipmentTypeEnum $shipmentType = null,
        /**
         * Shipment Date
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __ShipmentDate__ and __ShipmentDate__ are __mutually inclusive__.
         */
        public ?string $shipmentDate = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __ShipmentDate__ and __ShipmentDateCondition__ are __mutually
         * inclusive__.
         */
        public ?string $shipmentDateCondition = null,
        /**
         * Parameter to include custom free fields information in the result set, if
         * true then custom free fields will be included in the result set
         */
        public ?bool $includeCustomFreeFields = null,
    ) {}
}
