<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\SalesOrderLineOperationEnum;
use Pionect\VismaSdk\Enums\ShipmentShipmentTypeEnum;
use Pionect\VismaSdk\Enums\ShipmentStatusEnum;
use Spatie\LaravelData\Attributes\MapName;
use Spatie\LaravelData\Data as SpatieData;

/**
 * This class represents a Shipment in ShipmentController. Used by getting data.
 *
 * @method static \Pionect\VismaSdk\Factories\ShipmentDtoFactory testFactory()
 */
class ShipmentDto extends SpatieData
{
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        public ?string $timeStamp = null,
        /**
         * The top part > Shipment no > The unique reference number of the document,
         * which is automatically generated by the system.
         */
        public ?string $shipmentNumber = null,
        /**
         * The top part > Type > The type of the shipment document, which can be one of
         * the following options: Shipment, Transfer.
         */
        public ?ShipmentShipmentTypeEnum $shipmentType = null,
        /** The top part > Status > The status of the document. */
        public ?ShipmentStatusEnum $status = null,
        /**
         * The top part > Hold > This check box indicates (if selected) that the
         * documents cannot be processed further until the check box is cleared.
         */
        public ?bool $hold = null,
        /**
         * The top part > Operation > The operation to be performed in the Inventory
         * workspace for this shipment: Issue or Receipt.
         */
        public ?SalesOrderLineOperationEnum $operation = null,
        /**
         * Mandatory field: The top part > Shipment date* > The date when the document
         * has been created.
         */
        public ?\Carbon\Carbon $shipmentDate = null,
        public ?CustomerInShipmentDto $customer = null,
        public ?LocationInShipmentDto $location = null,
        public ?FromWarehouseInShipmentDto $fromWarehouse = null,
        public ?ToWarehouseInShipmentDto $toWarehouse = null,
        /**
         * Delivery settings tab > Freight currency > By default, it is the currency of
         * the sales order, but you can change it if needed.
         */
        public ?string $currencyId = null,
        public ?OwnerInShipmentDto $owner = null,
        /** The top part > Shipped quantity > The quantity of goods shipped. */
        public int|float|null $shippedQuantity = null,
        /** The top part > Shipped weight > The weight of the goods shipped. */
        public int|float|null $shippedWeight = null,
        /**
         * The top part > Shipped volume > The total volume of the items in the
         * shipment.
         */
        public int|float|null $shippedVolume = null,
        /** The top part > Packages > The number of boxes included in this shipment. */
        public ?int $packages = null,
        /**
         * The top part > Package weight > The total weight of the shipment that
         * includes the weight of boxes (for boxes determined automatically).
         */
        public int|float|null $packagesWeight = null,
        /**
         * The top part > Package volume > The total volume of the shipment that
         * includes the volume of boxes (for boxes determined automatically).
         */
        public int|float|null $packagesVolume = null,
        /**
         * The top part > Control quantity > The control value, which you manually enter
         * as a value equal to the shipped quantity if the Validate shipment total on
         * confirmation check box has been selected in the Sales orders preferences
         * (SO101000) window.
         */
        public int|float|null $controlQuantity = null,
        public ?DeliveryAddressInShipmentDto $deliveryAddress = null,
        public ?DeliveryContactInShipmentDto $deliveryContact = null,
        public ?ShipViaInShipmentDto $shipVia = null,
        public ?FobPointInShipmentDto $fobPoint = null,
        public ?ShippingTermsInShipmentDto $shippingTerms = null,
        public ?ShippingZoneInShipmentDto $shippingZone = null,
        /**
         * Delivery settings tab > Shipping information section > Residential delivery >
         * This check box indicates (if selected) that the shipping address is a
         * residential one.
         */
        public ?bool $residentialDelivery = null,
        /**
         * Delivery settings tab > Shipping information section > Saturday delivery >
         * This check box indicates delivery on saturday.
         */
        public ?bool $saturdayDelivery = null,
        public ?bool $useCustomerAccount = null,
        /**
         * Delivery settings tab > Shipping information section > Insurance > This check
         * box indicates (if selected) that insurance is required for the shipment.
         */
        public ?bool $insurance = null,
        /**
         * Delivery settings tab > Shipping information section > Freight cost > The
         * freight cost of the shipment.
         */
        public int|float|null $freightCost = null,
        /**
         * Delivery settings tab > Shipping information section > Freight amt. > The
         * amount of freight the customer will be charged for the shipment.
         */
        public int|float|null $freightAmt = null,
        public ?TransactionTypeInShipmentDto $transactionType = null,
        public ?ModeOfTrasportInShipmentDto $modeOfTrasport = null,
        /**
         * Delivery settings tab > Intrastat section > Container > This check box
         * indicates (if selected) that the shipment gets marked as shipped in container
         * for Intrastat reporting purposes.
         */
        public ?bool $container = null,
        /**
         * @var ShipmentDetailLineDto[]|null
         *                                   Document details tab >
         */
        public ?array $shipmentDetailLines = null,
        /**
         * @var ShipmentOrderLineDto[]|null
         *                                  Orders tab >
         */
        public ?array $shipmentOrderLines = null,
        /**
         * @var PackageDetailLineDto[]|null
         *                                  Packages tab >
         */
        public ?array $shipmentPackageLines = null,
        /** System generated information. */
        public ?\Carbon\Carbon $lastModifiedDateTime = null,
        public ?string $note = null,
        /** A free custom colum of type string with max length 100. */
        public ?string $customStr1 = null,
        /** A free custom colum of type string with max length 100. */
        public ?string $customStr2 = null,
        /** A free custom colum of type string with max length 100. */
        public ?string $customStr3 = null,
        /** A free custom colum of type string with max length 100. */
        public ?string $customStr4 = null,
        /** A free custom colum of type string with max length 100. */
        public ?string $customStr5 = null,
        /** A free custom colum of type decimal with max 4 decimals. */
        public int|float|null $customDec1 = null,
        /** A free custom colum of type decimal with max 4 decimals. */
        public int|float|null $customDec2 = null,
        /** A free custom colum of type int */
        public ?int $customInt1 = null,
        /** A free custom colum of type int */
        public ?int $customInt2 = null,
        /** A free custom colum of type DateTime - in UTC timezone */
        #[MapName('customDateTimeUTC1')]
        public ?\Carbon\Carbon $customDateTimeUtc1 = null,
        public ?string $errorInfo = null,
    ) {}
}
