<?php

namespace Pionect\VismaSdk\Dto;

use Pionect\VismaSdk\Enums\SupplierPaymentStatusEnum;
use Pionect\VismaSdk\Enums\SupplierPaymentTypeEnum;
use Spatie\LaravelData\Data as SpatieData;

/**
 * @method static \Pionect\VismaSdk\Factories\SupplierPaymentQueryParametersFactory testFactory()
 */
class SupplierPaymentQueryParameters extends SpatieData
{
    /** @use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory<\Pionect\VismaSdk\Factories\SupplierPaymentQueryParametersFactory> */
    use \Pionect\VismaSdk\Foundation\Factories\HasTestFactory;

    public function __construct(
        public ?string $invoiceRefNbr = null,
        /**
         * The top part > Type >The type of supplier ledger payment document. The
         * following types are available: Payment, PUrchase credit note, Prepayment,
         * Supplier refund, Voided payment.
         */
        public ?SupplierPaymentTypeEnum $paymentType = null,
        /** Enter the from-value for Ref. no. */
        public ?string $greaterThanValue = null,
        /**
         * This value, generated by the system, indicates the last time the record was
         * modified. Use it to retrieve all records that have been modified since that
         * time, up to the present.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd HH:mm:ss```
         * * ```yyyy-MM-dd HH:mm:ss.FFF```
         * * ```yyyy-MM-ddTHH:mm:ss```
         * * ```yyyy-MM-ddTHH:mm:ss.FFF```
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTime = null,
        /**
         * This value represents the condition to be applied when retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are
         * __mutually inclusive__.
         */
        public ?string $lastModifiedDateTimeCondition = null,
        /** Filter by Supplier */
        public ?string $supplier = null,
        /** Filter by Branch */
        public ?string $branch = null,
        /**
         * This value indicates the document date. Use it to retrieve all records that
         * have the Document Date since that time, up to the future.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         *
         * _Note:_ __DocDate__ and __DocDateCondition__ are __mutually inclusive__.
         */
        public ?\Carbon\Carbon $docDate = null,
        /**
         * This value represents the condition to be applied to the Document Date when
         * retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __DocDate__ and __DocDateCondition__ are __mutually inclusive__.
         */
        public ?string $docDateCondition = null,
        /**
         * This value indicates the date the document is due for payment. Use it to
         * retrieve all records that have the Due date since that time, up to the
         * future.
         *
         * Accepted format:
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         * * ```yyyy-MM-dd```
         *
         * _Note:_ __DueDate__ and __DueDateConditionCondition__ are __mutually
         * inclusive__.
         */
        public ?\Carbon\Carbon $dueDate = null,
        /**
         * This value represents the condition to be applied to the Due Date when
         * retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __DueDate__ and __DueDateCondition__ are __mutually inclusive__.
         */
        public ?string $dueDateCondition = null,
        /** Filter by financial period, format YYYYPP */
        public ?string $financialPeriod = null,
        /**
         * This value represents balance of the payment remaining to be applied and
         * released. Only released applications will count towards the balance.
         *
         * _Note:_ __Balance__ and __BalanceCondition__ are __mutually inclusive__.
         */
        public int|float|null $balance = null,
        /**
         * This value represents the condition to be applied to the Balance when
         * retrieving records.
         *
         * Accepted values (without the single quotes):
         * * '>' for greater than
         * * '<' for less than
         * * '>=' for greater than or equal
         * * '<=' for less than or equal
         *
         * _Note:_ __Balance__ and __BalanceCondition__ are __mutually inclusive__.
         */
        public ?string $balanceCondition = null,
        /** Filter by document status */
        public ?SupplierPaymentStatusEnum $status = null,
        /** Pagination parameter. Page number. */
        public ?int $pageNumber = null,
        /**
         * Pagination parameter. Number of items to be collected.
         * Please use a page size lower or equal to the allowed max page size which is
         * returned as part of the metadata information.
         * If requested page size is greater than allowed max page size, request will be
         * limited to max page size.
         */
        public ?int $pageSize = null,
    ) {}
}
