<?php

namespace Pionect\VismaSdk\Requests\ProjectBasic;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * ProjectBasic_GetAll
 */
class ProjectBasicGetAllCollectionRequest extends Request implements Paginatable
{
    protected Method $method = Method::GET;

    public function resolveEndpoint(): string
    {
        return '/v1/projectbasic';
    }

    /**
     * @param  null|string  $status  Select project status.
     * @param  null|string  $description  Project name/description
     * @param  null|string  $projectId  Identifies the Project
     * @param  null|string  $startDate  Project's start date
     * @param  null|bool  $nonProject  Set to true to return the non-project.
     * @param  null|string  $projectIdDesc  Identifies the Project by ID and description
     * @param  null|string  $publicId  Identifies the Project by its publicId
     * @param  null|string  $restrictedEmployee  Id of the employee where access restrictions apply
     * @param  null|int  $restrictedUser  Id of the odp user where access restrictions apply
     * @param  null|bool  $visibleInAp  If the project is visible in the Supplier ledger
     * @param  null|bool  $visibleInAr  If the project is visible in the Customer ledger
     * @param  null|bool  $visibleInCa  If the project is visible in the Cash management workspace
     * @param  null|bool  $visibleInCr  If the project is visible in the CRM workspace
     * @param  null|bool  $visibleInEa  If the project is visible in the Expense workspace
     * @param  null|bool  $visibleInGl  If the project is visible in the General ledger workspace
     * @param  null|bool  $visibleInIn  If the project is visible in the Inventory workspace
     * @param  null|bool  $visibleInPo  If the project is visible in the Purchases workspace
     * @param  null|bool  $visibleInSo  If the project is visible in the Sales workspace
     * @param  null|bool  $visibleInTa  If the project is visible in the Time entities workspace
     * @param  null|int  $numberToRead  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|int  $skipRecords  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|string  $greaterThanValue  Greater than value. The item which is the object for this, varies from API to API.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $createdDateTime  Creation date and time.
     * @param  null|string  $createdDateTimeCondition  System-retrieved information for state/condition
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?string $status = null,
        protected ?string $description = null,
        protected ?string $projectId = null,
        protected ?string $startDate = null,
        protected ?bool $nonProject = null,
        protected ?string $projectIdDesc = null,
        protected ?string $publicId = null,
        protected ?string $restrictedEmployee = null,
        protected ?int $restrictedUser = null,
        protected ?bool $visibleInAp = null,
        protected ?bool $visibleInAr = null,
        protected ?bool $visibleInCa = null,
        protected ?bool $visibleInCr = null,
        protected ?bool $visibleInEa = null,
        protected ?bool $visibleInGl = null,
        protected ?bool $visibleInIn = null,
        protected ?bool $visibleInPo = null,
        protected ?bool $visibleInSo = null,
        protected ?bool $visibleInTa = null,
        protected ?int $numberToRead = null,
        protected ?int $skipRecords = null,
        protected ?string $greaterThanValue = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?string $createdDateTime = null,
        protected ?string $createdDateTimeCondition = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'status' => $this->status,
            'description' => $this->description,
            'projectId' => $this->projectId,
            'startDate' => $this->startDate,
            'nonProject' => $this->nonProject,
            'projectIdDesc' => $this->projectIdDesc,
            'publicId' => $this->publicId,
            'restrictedEmployee' => $this->restrictedEmployee,
            'restrictedUser' => $this->restrictedUser,
            'visibleInAp' => $this->visibleInAp,
            'visibleInAr' => $this->visibleInAr,
            'visibleInCa' => $this->visibleInCa,
            'visibleInCr' => $this->visibleInCr,
            'visibleInEa' => $this->visibleInEa,
            'visibleInGl' => $this->visibleInGl,
            'visibleInIn' => $this->visibleInIn,
            'visibleInPo' => $this->visibleInPo,
            'visibleInSo' => $this->visibleInSo,
            'visibleInTa' => $this->visibleInTa,
            'numberToRead' => $this->numberToRead,
            'skipRecords' => $this->skipRecords,
            'greaterThanValue' => $this->greaterThanValue,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'createdDateTime' => $this->createdDateTime,
            'createdDateTimeCondition' => $this->createdDateTimeCondition,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
