<?php

namespace Pionect\VismaSdk\Requests\Customer;

use Pionect\VismaSdk\Dto\CustomerDocumentDto;
use Pionect\VismaSdk\Foundation\Hydration\Facades\Hydrator;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;

/**
 * Customer_GetAllDocumentsForCustomerBycustomerNumber
 */
class CustomerGetAllDocumentsForCustomerBycustomerNumberRequest extends Request
{
    protected $model = CustomerDocumentDto::class;

    protected Method $method = Method::GET;

    public function createDtoFromResponse(Response $response): mixed
    {
        return Hydrator::hydrate(
            $this->model,
            $response->json('data'),
            $response->json('included')
        );
    }

    public function resolveEndpoint(): string
    {
        return "/v1/customer/{$this->customerNumberId}/document";
    }

    /**
     * @param  string  $customerNumberId  Identifies the customer for which to return data
     * @param  null|string  $documentType  The field is deprecated for specific customer document endpoints. It will only be usable from customer document endpoint.
     * @param  null|int  $released  Parameter for showing if invoice has been released or not.
     * @param  null|int  $dunningLevel  The dunning level of the document.
     * @param  null|string  $closedFinancialPeriod  The date of the closing of the financial period.
     * @param  null|string  $dunningLetterDateTime  The date and time for when the document last released a dunning letter.
     * @param  null|string  $dunningLetterDateTimeCondition  Set time/date as before (&lt;), after (&gt;), before and including (=&lt;) OR after and including (=&gt;) to filter on time frame.
     * @param  null|string  $project  The project with which the document is associated.
     * @param  null|bool  $expandApplications  True if you want to see all dunning information regarding this document.
     * @param  null|bool  $expandAttachments  True if you want to see all attachments regarding this document.
     * @param  null|bool  $expandTaxDetails  True if you want to see all VAT details regarding this document.
     * @param  null|bool  $expandInvoiceAddress  True if you want to see all information regarding the invoice address for this document.
     * @param  null|string  $financialPeriod  The financial period to which the transactions recorded in the document is posted. Format YYYYMM.
     * @param  null|string  $documentDueDate  The date when payment for the document is due, in accordance with the credit terms.
     * @param  null|string  $documentDueDateCondition  This value represents the condition to be applied to the Due Date when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     * @param  null|string  $status  The status of the document. Use the dropdown to select status.
     * @param  null|int  $numberToRead  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|int  $skipRecords  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|string  $externalReference  The top part &gt; External reference &gt; The external reference used in AutoInvoice.
     * @param  null|string  $paymentReference  The top part &gt; Payment ref. &gt; The reference number of the document, as automatically generated by the system in accordance with the number series assigned to cash sales in the Customer ledger preferences window..
     * @param  null|string  $customerRefNumber  The top part &gt; External reference &gt; The external reference used in AutoInvoice.
     * @param  null|string  $customer  Filter by Customer
     * @param  null|string  $branch  Filter by Branch
     * @param  null|string  $documentDate  This value indicates the document date. Use it to retrieve all records that have the Document Date since that time, up to the future.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     *
     * _Note:_ __DocumentDate__ and __DocumentDateCondition__ are __mutually inclusive__.
     * @param  null|string  $documentDateCondition  This value represents the condition to be applied to the Document Date when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __DocumentDate__ and __DocumentDateCondition__ are __mutually inclusive__.
     * @param  null|string  $greaterThanValue  Greater than value. The item which is the object for this, varies from API to API.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $createdDateTime  Creation date and time.
     * @param  null|string  $createdDateTimeCondition  System-retrieved information for state/condition
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected string $customerNumberId,
        protected ?string $documentType = null,
        protected ?int $released = null,
        protected ?int $dunningLevel = null,
        protected ?string $closedFinancialPeriod = null,
        protected ?string $dunningLetterDateTime = null,
        protected ?string $dunningLetterDateTimeCondition = null,
        protected ?string $project = null,
        protected ?bool $expandApplications = null,
        protected ?bool $expandDunningInformation = null,
        protected ?bool $expandAttachments = null,
        protected ?bool $expandTaxDetails = null,
        protected ?bool $expandInvoiceAddress = null,
        protected ?string $financialPeriod = null,
        protected ?string $documentDueDate = null,
        protected ?string $documentDueDateCondition = null,
        protected ?string $status = null,
        protected ?int $numberToRead = null,
        protected ?int $skipRecords = null,
        protected ?string $externalReference = null,
        protected ?string $paymentReference = null,
        protected ?string $customerRefNumber = null,
        protected ?string $customer = null,
        protected ?string $branch = null,
        protected ?string $documentDate = null,
        protected ?string $documentDateCondition = null,
        protected ?string $greaterThanValue = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?string $createdDateTime = null,
        protected ?string $createdDateTimeCondition = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'documentType' => $this->documentType,
            'released' => $this->released,
            'dunningLevel' => $this->dunningLevel,
            'closedFinancialPeriod' => $this->closedFinancialPeriod,
            'dunningLetterDateTime' => $this->dunningLetterDateTime,
            'dunningLetterDateTimeCondition' => $this->dunningLetterDateTimeCondition,
            'project' => $this->project,
            'expandApplications' => $this->expandApplications,
            'expandDunningInformation' => $this->expandDunningInformation,
            'expandAttachments' => $this->expandAttachments,
            'expandTaxDetails' => $this->expandTaxDetails,
            'expandInvoiceAddress' => $this->expandInvoiceAddress,
            'financialPeriod' => $this->financialPeriod,
            'documentDueDate' => $this->documentDueDate,
            'documentDueDateCondition' => $this->documentDueDateCondition,
            'status' => $this->status,
            'numberToRead' => $this->numberToRead,
            'skipRecords' => $this->skipRecords,
            'externalReference' => $this->externalReference,
            'paymentReference' => $this->paymentReference,
            'customerRefNumber' => $this->customerRefNumber,
            'customer' => $this->customer,
            'branch' => $this->branch,
            'documentDate' => $this->documentDate,
            'documentDateCondition' => $this->documentDateCondition,
            'greaterThanValue' => $this->greaterThanValue,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'createdDateTime' => $this->createdDateTime,
            'createdDateTimeCondition' => $this->createdDateTimeCondition,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
