<?php

namespace Pionect\VismaSdk\Requests\Customer;

use Pionect\VismaSdk\Dto\CustomerDto;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * Customer_GetAll
 */
class CustomerGetAllRequest extends Request implements Paginatable
{
    protected $model = CustomerDto::class;

    protected Method $method = Method::GET;

    public function createDtoFromResponse(Response $response): mixed
    {
        $data = $response->json();

        return collect($data)->map(
            fn (array $item) => CustomerDto::from($item)
        );
    }

    public function resolveEndpoint(): string
    {
        return '/v1/customer';
    }

    /**
     * @param  null|string  $greaterThanValue  This field does not work and has been deprecated. It will be removed in future versions.
     * @param  null|int  $numberToRead  [This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.]
     *                                  Tells the service to return only {numberToRead} number of records.
     * @param  null|int  $skipRecords  [This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.]
     *                                 Tells the service to return only records after the first {skipRecords} number of records.
     * @param  null|string  $name  Equals Customer name.
     * @param  null|string  $status  Drop down and select Status.
     * @param  null|string  $corporateId  Equals Corporate ID from Delivery settings tab.
     * @param  null|string  $vatRegistrationId  Equals VAT registration ID from Delivery settings tab.
     * @param  null|string  $email  Equals Email for customer.
     * @param  null|string  $phone  Equals Phone 1 for customer.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|bool  $expandDirectDebit  Expand direct debit info
     * @param  null|string  $attributes  Attributes (additional information) connected to the entity.
     *                                   Examples:
     *                                   {{base}}/customer?attributes={"AttributeID":"ValueID","AttributeID":"ValueID"}
     *                                   {{base}}/customer?attributes={"AttributeID":"ValueID1,ValueID2"}
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?string $greaterThanValue = null,
        protected ?int $numberToRead = null,
        protected ?int $skipRecords = null,
        protected ?string $name = null,
        protected ?string $status = null,
        protected ?string $corporateId = null,
        protected ?string $vatRegistrationId = null,
        protected ?string $email = null,
        protected ?string $phone = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?string $createdDateTime = null,
        protected ?string $createdDateTimeCondition = null,
        protected ?bool $expandAccountInformation = null,
        protected ?bool $expandPaymentMethods = null,
        protected ?bool $expandDirectDebit = null,
        protected ?string $attributes = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'greaterThanValue' => $this->greaterThanValue,
            'numberToRead' => $this->numberToRead,
            'skipRecords' => $this->skipRecords,
            'name' => $this->name,
            'status' => $this->status,
            'corporateId' => $this->corporateId,
            'vatRegistrationId' => $this->vatRegistrationId,
            'email' => $this->email,
            'phone' => $this->phone,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'createdDateTime' => $this->createdDateTime,
            'createdDateTimeCondition' => $this->createdDateTimeCondition,
            'expandAccountInformation' => $this->expandAccountInformation,
            'expandPaymentMethods' => $this->expandPaymentMethods,
            'expandDirectDebit' => $this->expandDirectDebit,
            'attributes' => $this->attributes,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
