<?php

namespace Pionect\VismaSdk\Requests\Budget;

use Illuminate\Support\Collection;
use Pionect\VismaSdk\Dto\BudgetDto;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * Budget_GetAll
 */
class BudgetGetAllRequest extends Request implements Paginatable
{
    protected Method $method = Method::GET;

    /**
     * @return Collection<BudgetDto>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        $data = $response->json();

        return collect($data)->map(
            fn (array $item) => BudgetDto::from($item)
        );
    }

    public function resolveEndpoint(): string
    {
        return '/v1/budget';
    }

    /**
     * @param  null|bool  $isReleased  True to get released budgets.
     * @param  null|string  $greaterThanValue  Filter by from date.
     * @param  null|int  $numberToRead  This field has been deprecated and will be removed in future versions.
     * @param  null|int  $skipRecords  This field has been deprecated and will be removed in future versions.
     * @param  null|string  $orderBy  Order by Last modified date and time.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  string  $branch  Mandatory. Filter by budgets Branch.
     * @param  string  $ledger  Mandatory. The budgets Ledger
     * @param  string  $financialYear  The budgets financial year.
     * @param  null|string  $subaccount  The Subaccount of the budget article.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?bool $isReleased,
        protected ?string $greaterThanValue,
        protected ?int $numberToRead,
        protected ?int $skipRecords,
        protected ?string $orderBy,
        protected ?string $lastModifiedDateTime,
        protected ?string $lastModifiedDateTimeCondition,
        protected string $branch,
        protected string $ledger,
        protected string $financialYear,
        protected ?string $subaccount = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'isReleased' => $this->isReleased,
            'greaterThanValue' => $this->greaterThanValue,
            'numberToRead' => $this->numberToRead,
            'skipRecords' => $this->skipRecords,
            'orderBy' => $this->orderBy,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'branch' => $this->branch,
            'ledger' => $this->ledger,
            'financialYear' => $this->financialYear,
            'subaccount' => $this->subaccount,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
