<?php

namespace Pionect\VismaSdk\Requests\ProjectTransaction;

use Illuminate\Support\Collection;
use Pionect\VismaSdk\Dto\ProjectTransactionDocumentDto;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * ProjectTransaction_GetAll
 *
 * Data for Project transactions
 */
class ProjectTransactionGetAllRequest extends Request implements Paginatable
{
    protected Method $method = Method::GET;

    /**
     * @return Collection<ProjectTransactionDocumentDto>
     */
    public function createDtoFromResponse(Response $response): Collection
    {
        $data = $response->json();

        return collect($data)->map(
            fn (array $item) => ProjectTransactionDocumentDto::from($item)
        );
    }

    public function resolveEndpoint(): string
    {
        return '/v1/projecttransaction';
    }

    /**
     * @param  null|string  $module  Select to filter on module; e.g. AR, AP, IN etc.
     * @param  null|string  $status  The status of the document.
     * @param  null|string  $project  Filter on project ID.
     * @param  null|string  $projectTask  Filter on Task ID.
     * @param  null|bool  $billable  Filter invoiceable project tasks.
     * @param  null|string  $branch  Filter on branch for the project transation.
     * @param  null|string  $date  Filter on the registration date for the project transaction.
     * @param  null|string  $fromPeriod  Mandatory. Start date for the task.
     * @param  null|string  $toPeriod  Mandatory. End date for the task.
     * @param  null|int  $numberToRead  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|int  $skipRecords  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|bool  $expandNote  Expands project transaction notes
     * @param  null|string  $greaterThanValue  Greater than value. The item which is the object for this, varies from API to API.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $createdDateTime  Creation date and time.
     * @param  null|string  $createdDateTimeCondition  System-retrieved information for state/condition
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?string $module = null,
        protected ?string $status = null,
        protected ?string $project = null,
        protected ?string $projectTask = null,
        protected ?bool $billable = null,
        protected ?string $branch = null,
        protected ?string $date = null,
        protected ?string $fromPeriod = null,
        protected ?string $toPeriod = null,
        protected ?int $numberToRead = null,
        protected ?int $skipRecords = null,
        protected ?bool $expandNote = null,
        protected ?string $greaterThanValue = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?string $createdDateTime = null,
        protected ?string $createdDateTimeCondition = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'module' => $this->module,
            'status' => $this->status,
            'project' => $this->project,
            'projectTask' => $this->projectTask,
            'billable' => $this->billable,
            'branch' => $this->branch,
            'date' => $this->date,
            'fromPeriod' => $this->fromPeriod,
            'toPeriod' => $this->toPeriod,
            'numberToRead' => $this->numberToRead,
            'skipRecords' => $this->skipRecords,
            'expandNote' => $this->expandNote,
            'greaterThanValue' => $this->greaterThanValue,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'createdDateTime' => $this->createdDateTime,
            'createdDateTimeCondition' => $this->createdDateTimeCondition,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
