<?php

namespace Pionect\VismaSdk\Requests\JournalTransactionV2;

use Pionect\VismaSdk\Dto\JournalTransactionDto;
use Pionect\VismaSdk\Foundation\Hydration\Facades\Hydrator;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * JournalTransactionV2_GetAllJournalTransactions
 *
 * Data for Journal Transaction
 */
class JournalTransactionV2GetAllJournalTransactionsCollectionRequest extends Request implements Paginatable
{
    protected $model = JournalTransactionDto::class;

    protected Method $method = Method::GET;

    public function createDtoFromResponse(Response $response): mixed
    {
        return Hydrator::hydrateCollection(
            $this->model,
            $response->json()
        );
    }

    public function resolveEndpoint(): string
    {
        return '/v2/journaltransaction';
    }

    /**
     * @param  null|string  $periodId  Financial Period to query data for. Mandatory if 'LastModifiedDateTime' not provided. Format: YYYYPP
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *                                             Mandatory if 'PeriodId' is not provided.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     * @param  null|string  $module  Module to query data for. Allowed values: GL, AP, AR, CM, CA, IN, DR, FA, PM
     * @param  null|string  $status  Journal transaction status to query data for. Available statuses : Hold, Balanced, Unposted, Posted, Voided, Scheduled, Unreleased.
     * @param  null|bool  $expandAttachments  If true, includes all attachments for batch. Default is false.
     * @param  null|string  $branch  Branch to query data for.
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?string $periodId = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $module = null,
        protected ?string $status = null,
        protected ?bool $expandAttachments = null,
        protected ?string $branch = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'periodId' => $this->periodId,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'module' => $this->module,
            'status' => $this->status,
            'expandAttachments' => $this->expandAttachments,
            'branch' => $this->branch,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
