<?php

namespace Pionect\VismaSdk\Requests\InventoryIssue;

use Pionect\VismaSdk\Dto\InventoryIssueDto;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * InventoryIssue_GetAll
 */
class InventoryIssueGetAllRequest extends Request implements Paginatable
{
    protected $model = InventoryIssueDto::class;

    protected Method $method = Method::GET;

    public function createDtoFromResponse(Response $response): mixed
    {
        $data = $response->json();

        return collect($data)->map(
            fn (array $item) => InventoryIssueDto::from($item)
        );
    }

    public function resolveEndpoint(): string
    {
        return '/v1/inventoryissue';
    }

    /**
     * @param  null|string  $date  The date when the inventory document was created
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __Date__ and __DateCondition__ are __mutually inclusive__.
     * @param  null|string  $dateCondition  This value represents the condition to be applied when retrieving records usind the __Date__ filter.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __Date__ and __DateCondition__ are __mutually inclusive__.
     * @param  null|int  $numberToRead  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|int  $skipRecords  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|string  $orderBy  This field has been deprecated and will be removed in future versions. The OrderBy parameter has no effect on the result.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?string $status = null,
        protected ?string $date = null,
        protected ?string $dateCondition = null,
        protected ?string $greaterThanValue = null,
        protected ?int $numberToRead = null,
        protected ?int $skipRecords = null,
        protected ?string $orderBy = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'status' => $this->status,
            'date' => $this->date,
            'dateCondition' => $this->dateCondition,
            'greaterThanValue' => $this->greaterThanValue,
            'numberToRead' => $this->numberToRead,
            'skipRecords' => $this->skipRecords,
            'orderBy' => $this->orderBy,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
