<?php

declare(strict_types=1);

namespace Pionect\VismaSdk\Generator\Generators;

use Crescat\SaloonSdkGenerator\Data\Generator\ApiSpecification;
use Crescat\SaloonSdkGenerator\Generators\ConnectorGenerator;
use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\PhpFile;

class PlainJsonConnectorGenerator extends ConnectorGenerator
{
    protected function generateConnectorClass(ApiSpecification $specification): ?PhpFile
    {
        $phpFile = parent::generateConnectorClass($specification); // TODO: Change the autogenerated stub

        // Get the namespace and class
        $namespace = array_values($phpFile->getNamespaces())[0];
        /** @var ClassType $classType */
        $classType = array_values($namespace->getClasses())[0];

        // Override constructor to use property promotion (ServiceProvider injects the token)
        if ($classType->hasMethod('__construct')) {
            $constructor = $classType->getMethod('__construct');
            // Clear existing parameters
            foreach ($constructor->getParameters() as $param) {
                $constructor->removeParameter($param->getName());
            }
        }

        return $phpFile;
    }
}
