<?php

namespace Pionect\VismaSdk\Requests\SupplierPayment;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * SupplierPayment_GetAllPayments
 */
class SupplierPaymentGetAllPaymentsCollectionRequest extends Request implements Paginatable
{
    protected Method $method = Method::GET;

    public function resolveEndpoint(): string
    {
        return '/v1/supplierPayment';
    }

    /**
     * @param  null|string  $paymentType  The top part &gt; Type &gt;The type of supplier ledger payment document. The following types are available: Payment, PUrchase credit note, Prepayment, Supplier refund, Voided payment.
     * @param  null|string  $greaterThanValue  Enter the from-value for Ref. no.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $supplier  Filter by Supplier
     * @param  null|string  $branch  Filter by Branch
     * @param  null|string  $docDate  This value indicates the document date. Use it to retrieve all records that have the Document Date since that time, up to the future.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     *
     * _Note:_ __DocDate__ and __DocDateCondition__ are __mutually inclusive__.
     * @param  null|string  $docDateCondition  This value represents the condition to be applied to the Document Date when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __DocDate__ and __DocDateCondition__ are __mutually inclusive__.
     * @param  null|string  $dueDate  This value indicates the date the document is due for payment. Use it to retrieve all records that have the Due date since that time, up to the future.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     *
     * _Note:_ __DueDate__ and __DueDateConditionCondition__ are __mutually inclusive__.
     * @param  null|string  $dueDateCondition  This value represents the condition to be applied to the Due Date when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __DueDate__ and __DueDateCondition__ are __mutually inclusive__.
     * @param  null|string  $financialPeriod  Filter by financial period, format YYYYPP
     * @param  null|float|int  $balance  This value represents balance of the payment remaining to be applied and released. Only released applications will count towards the balance.
     *
     * _Note:_ __Balance__ and __BalanceCondition__ are __mutually inclusive__.
     * @param  null|string  $balanceCondition  This value represents the condition to be applied to the Balance when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __Balance__ and __BalanceCondition__ are __mutually inclusive__.
     * @param  null|string  $status  Filter by document status
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?string $invoiceRefNbr = null,
        protected ?string $paymentType = null,
        protected ?string $greaterThanValue = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?string $supplier = null,
        protected ?string $branch = null,
        protected ?string $docDate = null,
        protected ?string $docDateCondition = null,
        protected ?string $dueDate = null,
        protected ?string $dueDateCondition = null,
        protected ?string $financialPeriod = null,
        protected float|int|null $balance = null,
        protected ?string $balanceCondition = null,
        protected ?string $status = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'invoiceRefNbr' => $this->invoiceRefNbr,
            'paymentType' => $this->paymentType,
            'greaterThanValue' => $this->greaterThanValue,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'supplier' => $this->supplier,
            'branch' => $this->branch,
            'docDate' => $this->docDate,
            'docDateCondition' => $this->docDateCondition,
            'dueDate' => $this->dueDate,
            'dueDateCondition' => $this->dueDateCondition,
            'financialPeriod' => $this->financialPeriod,
            'balance' => $this->balance,
            'balanceCondition' => $this->balanceCondition,
            'status' => $this->status,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
