<?php

namespace Pionect\VismaSdk\Requests\CustomerPayment;

use Pionect\VismaSdk\Dto\PaymentDto;
use Pionect\VismaSdk\Foundation\Hydration\Facades\Hydrator;
use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;
use Saloon\PaginationPlugin\Contracts\Paginatable;

/**
 * CustomerPayment_GetAllPayments
 */
class CustomerPaymentGetAllPaymentsCollectionRequest extends Request implements Paginatable
{
    protected $model = PaymentDto::class;

    protected Method $method = Method::GET;

    public function createDtoFromResponse(Response $response): mixed
    {
        return Hydrator::hydrateCollection(
            $this->model,
            $response->json()
        );
    }

    public function resolveEndpoint(): string
    {
        return '/v1/customerPayment';
    }

    /**
     * @param  null|string  $paymentNbr  Payment number
     * @param  null|string  $customer  Enter Customer
     * @param  null|string  $greaterThanValue  Enter the from-value for Ref. no.
     * @param  null|string  $invoiceRefNbr  Enter Invoice Ref Nbr
     * @param  null|string  $status  The status of the document. Use the dropdown to select status.
     * @param  null|int  $numberToRead  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|int  $skipRecords  This field has been deprecated and will be removed in future versions. Use pagenumber and pagesize for pagination purposes. Pagenumber and pagesize does not work with NumberToRead and SkipRecords.
     * @param  null|string  $orderBy  Enter field to order your records by.
     * @param  null|string  $lastModifiedDateTime  This value, generated by the system, indicates the last time the record was modified. Use it to retrieve all records that have been modified since that time, up to the present.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd HH:mm:ss```
     * * ```yyyy-MM-dd HH:mm:ss.FFF```
     * * ```yyyy-MM-ddTHH:mm:ss```
     * * ```yyyy-MM-ddTHH:mm:ss.FFF```
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $lastModifiedDateTimeCondition  This value represents the condition to be applied when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __LastModifiedDateTime__ and __LastModifiedDateTimeCondition__ are __mutually inclusive__.
     * @param  null|string  $branch  Filter by Branch
     * @param  null|string  $docDate  This value indicates the document date. Use it to retrieve all records that have the Document Date since that time, up to the future.
     *
     * Accepted format:
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     * * ```yyyy-MM-dd```
     *
     * _Note:_ __DocDate__ and __DocDateCondition__ are __mutually inclusive__.
     * @param  null|string  $docDateCondition  This value represents the condition to be applied to the Document Date when retrieving records.
     *
     * Accepted values (without the single quotes):
     * * '&gt;' for greater than
     * * '&lt;' for less than
     * * '&gt;=' for greater than or equal
     * * '&lt;=' for less than or equal
     *
     * _Note:_ __DocDate__ and __DocDateCondition__ are __mutually inclusive__.
     * @param  null|string  $financialPeriod  Filter by financial period, format YYYYPP
     * @param  null|int  $pageNumber  Pagination parameter. Page number.
     * @param  null|int  $pageSize  Pagination parameter. Number of items to be collected.
     *                              Please use a page size lower or equal to the allowed max page size which is returned as part of the metadata information.
     *                              If requested page size is greater than allowed max page size, request will be limited to max page size.
     * @param  null|string  $erpApiBackground  Accepts the request and queues it to be executed in the background by our least busy worker. Responds with 202 Accepted and a document containing a JobId reference and details state location.
     *                                         Supported values:
     *                                         * a URL: when the background operation is finished, a notification will be posted to the URL with a document containing a reference id, status code and a details state location.
     *                                         * "none" (without quotes): Fire and forget; no notification will be sent when background operation is finished.
     *                                         * "subscription[:<name_1>=<value_1>,..,<name_n>=<value_n>]" (without quotes): when the background operation is finsihed, a notification is posted to the Webhook subscription set up in Developer Portal for your integration client.
     *                                         Optionally a set of name-value pairs can be added. These will be sent as headers in the POST request to the Webhook subscription's url.
     *
     * To find status and details of a background-api operation, GET .. v1/background/{id}. To get the response payload of a background-api operation, if any, GET .. v1/background/{id}/content
     */
    public function __construct(
        protected ?string $paymentNbr = null,
        protected ?string $paymentType = null,
        protected ?string $customer = null,
        protected ?string $greaterThanValue = null,
        protected ?string $invoiceRefNbr = null,
        protected ?string $status = null,
        protected ?int $numberToRead = null,
        protected ?int $skipRecords = null,
        protected ?string $orderBy = null,
        protected ?string $lastModifiedDateTime = null,
        protected ?string $lastModifiedDateTimeCondition = null,
        protected ?string $branch = null,
        protected ?string $docDate = null,
        protected ?string $docDateCondition = null,
        protected ?string $financialPeriod = null,
        protected ?int $pageNumber = null,
        protected ?int $pageSize = null,
        protected ?string $erpApiBackground = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter([
            'paymentNbr' => $this->paymentNbr,
            'paymentType' => $this->paymentType,
            'customer' => $this->customer,
            'greaterThanValue' => $this->greaterThanValue,
            'invoiceRefNbr' => $this->invoiceRefNbr,
            'status' => $this->status,
            'numberToRead' => $this->numberToRead,
            'skipRecords' => $this->skipRecords,
            'orderBy' => $this->orderBy,
            'lastModifiedDateTime' => $this->lastModifiedDateTime,
            'lastModifiedDateTimeCondition' => $this->lastModifiedDateTimeCondition,
            'branch' => $this->branch,
            'docDate' => $this->docDate,
            'docDateCondition' => $this->docDateCondition,
            'financialPeriod' => $this->financialPeriod,
            'pageNumber' => $this->pageNumber,
            'pageSize' => $this->pageSize,
        ]);
    }

    public function defaultHeaders(): array
    {
        return array_filter(['erp-api-background' => $this->erpApiBackground]);
    }
}
